/* eslint-disable */
// @ts-nocheck
/*
 * swotData.ts — data tables for the SWOT Compass feature.
 *
 * The I18N dictionary, QUADS/STEPS/LIKERT/TEXTS constants and the BENCHMARKS
 * industry knowledge base are extracted VERBATIM from the original standalone
 * SWOT Compass tool so the ported feature matches it exactly. Do not hand-edit
 * these blocks — regenerate via scripts/extract_swot if the source changes.
 *
 * The engine (deriveSWOT/detectRung) and the React UI live in swotEngine.ts and
 * SwotCompass.tsx respectively. A hospitality/bakery benchmark profile is added
 * on top of these (see swotEngine.getBenchmarks) rather than edited in here.
 */

export const I18N = {
en: {
  tagline:"Your personal growth, mapped.", signOut:"Sign out",
  navAdmin:"Admin Console", navMySwot:"My SWOT",
  authTitle:"Welcome", authSubtitle:"Your private space to reflect, plan and grow professionally.",
  emailLabel:"Email address", emailPlaceholder:"you@company.com", continueBtn:"Continue",
  newUserNotice:"You're new here — set your password to create your account.",
  returningNotice:"Welcome back! Enter your password to sign in.",
  nameLabel:"Full name", namePlaceholder:"e.g. Priya Sharma",
  passwordLabel:"Password", confirmPasswordLabel:"Confirm password",
  createAccountBtn:"Create account", signInBtn:"Sign in", backBtn:"Back",
  demoHint:"Demo admin: admin@cakewala.in · password: admin123",
  errEmail:"Please enter a valid email address.", errName:"Please enter your name.",
  errPasswordShort:"Password must be at least 6 characters.", errPasswordMismatch:"Passwords do not match.",
  errWrongPassword:"Incorrect password. Please try again.",
  toastWelcome:"Welcome back, {name}!", toastAccountCreated:"Account created. Welcome, {name}!",
  qTitle:"Smart SWOT Questionnaire", qIntro:"You don't need to know your own SWOT — just answer simply and honestly. The program reads your responses and builds it for you.",
  stepWork:"How you work", stepStories:"Your experiences", stepEnv:"Your environment",
  workIntro:"Rate how well each statement describes you. There are no right or wrong answers.",
  storiesIntro:"Describe in your own words — the program reads your descriptions to find your strengths and weaknesses.",
  envIntro:"Now a few statements about the world around your role.",
  scaleLow:"Strongly disagree", scaleHigh:"Strongly agree",
  lkHelp:"Colleagues regularly come to me for help or advice in my area of work.",
  lkDeadline:"I finish my work on or before deadline, even without reminders.",
  lkPresent:"I feel confident explaining my ideas to senior people or groups.",
  lkPostpone:"I often postpone tasks that feel difficult, unclear or boring.",
  lkLearn:"I pick up new tools and methods faster than most of my peers.",
  lkNo:"I find it hard to say no, so I often end up with too much on my plate.",
  lkGrowth:"My industry is growing and creating new kinds of roles.",
  lkNetwork:"I regularly talk to people outside my team who could help my career.",
  lkAuto:"A big part of my daily tasks could be done by software or AI.",
  lkPace:"The skills my role demands are changing faster than I am learning them.",
  lkTrain:"My organisation offers training, mentoring or projects I could join.",
  tpProud:"Describe one recent piece of work you are proud of. What exactly did you do well?",
  tpDrain:"Which task do you keep postponing or find most draining? What makes it hard for you?",
  tpFeedback:"What comment about you — praise or criticism — have you heard more than once at work?",
  tpFuture:"What changes do you expect in your field over the next 2–3 years? (new tech, competition, demand…)",
  storyPlaceholder:"Write a few honest sentences…",
  errLikert:"Please answer all the statements in this section.",
  errStories:"Please fill in at least one description.",
  fromYourWords:"In your own words:",
  derivedNote:"These insights were derived automatically from your questionnaire answers and descriptions.",
  dvHelpHigh:"Go-to expert — colleagues actively seek your knowledge.",
  dvHelpLow:"Low visibility — your expertise is not yet recognised by colleagues.",
  dvDeadlineHigh:"Reliable delivery — you meet deadlines without supervision.",
  dvDeadlineLow:"Time management — deadlines tend to slip without external pressure.",
  dvPresentHigh:"Confident communicator, comfortable with senior audiences.",
  dvPresentLow:"Presentation confidence — sharing ideas with seniors feels difficult.",
  dvPostponeHigh:"Procrastination — difficult or unclear tasks get postponed.",
  dvPostponeLow:"Strong self-discipline — you tackle hard tasks head-on.",
  dvLearnHigh:"Fast learner — you absorb new tools quicker than peers.",
  dvLearnLow:"Learning pace — new tools and methods take you extra time.",
  dvNoHigh:"Overcommitment — difficulty saying no leads to overload.",
  dvNoLow:"Healthy boundaries — you manage your workload deliberately.",
  dvGrowthHigh:"A growing industry is creating new roles around you.",
  dvGrowthLow:"A stagnant industry may limit openings in your field.",
  dvNetworkHigh:"Your network beyond the team can open unexpected doors.",
  dvNetworkLow:"Limited professional network outside your immediate team.",
  dvAutoHigh:"Automation exposure — part of your routine work could be automated.",
  dvPaceHigh:"Skill-gap risk — role demands are moving faster than your learning.",
  dvPaceLow:"You are keeping pace with your role's evolving demands.",
  dvTrainHigh:"Internal training, mentoring and projects are there for the taking.",
  dvTrainLow:"Few internal growth resources — development depends on your own initiative.",
  dvDefaultS:"Consistent, dependable day-to-day performance.",
  dvDefaultW:"No major weakness surfaced — stay alert to blind spots.",
  dvDefaultO:"Growing use of AI tools in every industry — learn them early.",
  dvDefaultT:"General market shifts — keep your skills current.",
  stepOf:"Step {n} of {total}",
  stepProfile:"Profile", stepStrengths:"Strengths", stepWeaknesses:"Weaknesses", stepOpportunities:"Opportunities", stepThreats:"Threats",
  profileTitle:"Tell us about your role",
  roleLabel:"Job title / role", rolePlaceholder:"e.g. Product Manager",
  industryLabel:"Industry", industryPlaceholder:"e.g. Technology, Finance, Healthcare",
  smartAssistBtn:"Smart Assist", smartAssistHint:"Fetches industry-standard benchmarks for your profile.",
  smartAssistLoading:"Analysing industry benchmarks…", smartAssistTitle:"Benchmarks for your profile",
  saSkills:"Expected core skills", saTrends:"Trends to watch",
  attachTitle:"Attach a document (optional)", attachHint:"Résumé, SOP or performance review — its context is woven into your analysis.",
  attachBtn:"Choose file", attachedMsg:"Attached: {file}",
  internalTag:"Internal", externalTag:"External",
  sIntro:"What you already do well.",
  sQ1:"What core skills do colleagues rely on you for?", sQ2:"What achievement are you most proud of this year?", sQ3:"What unique advantage do you have over peers in similar roles?",
  wIntro:"Where you have room to grow.",
  wQ1:"Which skill gap slows you down most often?", wQ2:"What resources or support do you currently lack?", wQ3:"Which tasks do you tend to procrastinate on?",
  oIntro:"External possibilities you could seize.",
  oQ1:"Which industry trend could you ride in the next 1–2 years?", oQ2:"Which people or networks could open doors for you?", oQ3:"Which upcoming technology or skill would boost your value?",
  tIntro:"External risks worth preparing for.",
  tQ1:"Where is competition in your job market strongest?", tQ2:"Which parts of your role could automation or AI change?", tQ3:"How are the requirements of your role changing?",
  moreDetails:"Add more details (optional)", moreDetailsPlaceholder:"Anything else you'd like the analysis to consider…",
  nextBtn:"Next", prevBtn:"Previous", submitBtn:"Generate my analysis",
  errAnswerOne:"Please answer at least one question in this section.", errProfile:"Please fill in your role and industry.",
  toastSaved:"Analysis saved. Great work!",
  dashTitle:"Your Personal SWOT Analysis",
  strengths:"Strengths", weaknesses:"Weaknesses", opportunities:"Opportunities", threats:"Threats",
  attachedContext:"Context from “{file}” was incorporated into this analysis.",
  growthTitle:"Growth Guide & Next Steps",
  roadmapTitle:"Career Roadmap & Upskilling Guide",
  roadmapIntro:"Matched to your role and industry profile.",
  upskillTitle:"Skills to build now",
  coursesTitle:"Recommended courses & certifications",
  nextLevelTitle:"How to move to the next level",
  caseStudyTitle:"Real-world case studies",
  storyTitle:"Real-world inspiration",
  takeawayLabel:"Takeaway",
  successionTitle:"Career Succession Path",
  successionIntro:"A typical role ladder in this field, matched to your job title.",
  youAreHereBadge:"You are here",
  nextMoveLabel:"Typical next move",
  focusLabel:"Focus",
  gSO:"Exploit: Strength → Opportunity", gWO:"Improve: Opportunity → Weakness", gST:"Defend: Strength vs Threat", gWT:"Mitigate: Weakness × Threat",
  tplSO:"Pair your strength “{s}” with the opportunity “{o}”. Volunteer for work where this combination is visible to decision-makers.",
  tplWO:"Use “{o}” as a structured way to work on “{w}” — growth sticks best when attached to something new and exciting.",
  tplST:"Your strength “{s}” is your best defence against “{t}”. Keep it sharp, and make sure it is known beyond your immediate team.",
  tplWT:"“{w}” combined with “{t}” is your highest-risk zone. Build a 90-day improvement plan and find a mentor or course to close the gap.",
  planTitle:"Suggested 30 / 60 / 90-day plan",
  plan30:"Days 1–30: Document your strengths and share one visible win with your manager.",
  plan60:"Days 31–60: Start one course or project that targets your top weakness.",
  plan90:"Days 61–90: Act on one opportunity — a certification, a network, or a stretch assignment.",
  retakeBtn:"Retake questionnaire", downloadPdfBtn:"Download PDF",
  adminTitle:"Universal Admin Console", adminSubtitle:"Team overview, user management and aggregated insights.",
  mUsers:"Total users", mCompleted:"Analyses completed", mRate:"Completion rate", mPending:"Pending",
  themesTitle:"Common Themes", themesStrengths:"Top strengths across the team", themesThreats:"Top threats across the team", themesEmpty:"Not enough data yet.",
  viewBtn:"View", backToConsole:"Back to console",
  vaTitle:"Team SWOT Analysis", vaSelectUser:"Team member", vaNewest:"Newest first", vaOldest:"Oldest first",
  vaCompletedOn:"Completed on {date}", vaNone:"No completed analyses yet.",
  usersTitle:"User Management",
  colName:"Name", colEmail:"Email", colCreated:"Created", colStatus:"Status", colActions:"Actions",
  statusDone:"Completed", statusPending:"Pending",
  addUserBtn:"Add New User", resetPwdBtn:"Reset Password", deleteBtn:"Delete", adminBadge:"Admin",
  confirmDeleteTitle:"Delete user?", confirmDelete:"Delete {name} and their analysis? This cannot be undone.",
  toastUserAdded:"User {name} added.", toastUserDeleted:"User deleted.", toastPwdReset:"Password reset to “{pwd}”.",
  errUserExists:"A user with this email already exists.",
  modalAddTitle:"Add New User", modalRole:"Role", roleUser:"User", roleAdmin:"Admin", modalDefaultPwd:"Initial password",
  saveBtn:"Save", cancelBtn:"Cancel", confirmBtn:"Delete", emptyAnswer:"—"
},
hi: {
  tagline:"आपकी व्यक्तिगत प्रगति, एक नक्शे में।", signOut:"साइन आउट",
  navAdmin:"एडमिन कंसोल", navMySwot:"मेरा SWOT",
  authTitle:"स्वागत है", authSubtitle:"पेशेवर रूप से सोचने, योजना बनाने और आगे बढ़ने के लिए आपका निजी स्थान।",
  emailLabel:"ईमेल पता", emailPlaceholder:"aap@company.com", continueBtn:"आगे बढ़ें",
  newUserNotice:"आप यहाँ नए हैं — खाता बनाने के लिए अपना पासवर्ड सेट करें।",
  returningNotice:"वापसी पर स्वागत है! साइन इन करने के लिए पासवर्ड दर्ज करें।",
  nameLabel:"पूरा नाम", namePlaceholder:"जैसे प्रिया शर्मा",
  passwordLabel:"पासवर्ड", confirmPasswordLabel:"पासवर्ड की पुष्टि करें",
  createAccountBtn:"खाता बनाएँ", signInBtn:"साइन इन करें", backBtn:"वापस",
  demoHint:"डेमो एडमिन: admin@cakewala.in · पासवर्ड: admin123",
  errEmail:"कृपया मान्य ईमेल पता दर्ज करें।", errName:"कृपया अपना नाम दर्ज करें।",
  errPasswordShort:"पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।", errPasswordMismatch:"पासवर्ड मेल नहीं खाते।",
  errWrongPassword:"गलत पासवर्ड। कृपया पुनः प्रयास करें।",
  toastWelcome:"वापसी पर स्वागत है, {name}!", toastAccountCreated:"खाता बन गया। स्वागत है, {name}!",
  qTitle:"स्मार्ट SWOT प्रश्नावली", qIntro:"आपको अपना SWOT जानने की ज़रूरत नहीं — बस सरल और ईमानदार उत्तर दें। प्रोग्राम आपके उत्तर पढ़कर उसे स्वयं तैयार करेगा।",
  stepWork:"कार्यशैली", stepStories:"आपके अनुभव", stepEnv:"आपका परिवेश",
  workIntro:"बताएँ कि हर कथन आप पर कितना लागू होता है। कोई सही या गलत उत्तर नहीं है।",
  storiesIntro:"अपने शब्दों में लिखें — प्रोग्राम आपके विवरण पढ़कर आपकी ताकतें और कमज़ोरियाँ खोजेगा।",
  envIntro:"अब आपकी भूमिका के आसपास की दुनिया के बारे में कुछ कथन।",
  scaleLow:"बिल्कुल सहमत नहीं", scaleHigh:"पूरी तरह सहमत",
  lkHelp:"सहकर्मी अक्सर मेरे काम के क्षेत्र में मदद या सलाह के लिए मेरे पास आते हैं।",
  lkDeadline:"मैं बिना याद दिलाए अपना काम समयसीमा पर या पहले पूरा कर देता/देती हूँ।",
  lkPresent:"वरिष्ठ लोगों या समूहों के सामने अपने विचार रखने में मुझे आत्मविश्वास रहता है।",
  lkPostpone:"कठिन, अस्पष्ट या उबाऊ लगने वाले कार्यों को मैं अक्सर टाल देता/देती हूँ।",
  lkLearn:"नए टूल और तरीके मैं अपने साथियों से जल्दी सीख लेता/लेती हूँ।",
  lkNo:"मुझे 'ना' कहना कठिन लगता है, इसलिए अक्सर काम का बोझ बढ़ जाता है।",
  lkGrowth:"मेरा उद्योग बढ़ रहा है और नई तरह की भूमिकाएँ बन रही हैं।",
  lkNetwork:"मैं नियमित रूप से टीम के बाहर ऐसे लोगों से मिलता/मिलती हूँ जो मेरे करियर में मदद कर सकते हैं।",
  lkAuto:"मेरे दैनिक कार्यों का बड़ा हिस्सा सॉफ़्टवेयर या AI कर सकता है।",
  lkPace:"मेरी भूमिका की ज़रूरी स्किल्स मेरी सीखने की गति से तेज़ बदल रही हैं।",
  lkTrain:"मेरा संगठन प्रशिक्षण, मेंटरिंग या ऐसे प्रोजेक्ट देता है जिनसे मैं जुड़ सकता/सकती हूँ।",
  tpProud:"हाल का कोई काम बताइए जिस पर आपको गर्व है। आपने क्या खास अच्छा किया?",
  tpDrain:"कौन-सा काम आप टालते रहते हैं या जो आपको सबसे ज़्यादा थकाता है? वह कठिन क्यों लगता है?",
  tpFeedback:"आपके बारे में कौन-सी बात — प्रशंसा या आलोचना — आपने काम पर एक से अधिक बार सुनी है?",
  tpFuture:"अगले 2–3 वर्षों में अपने क्षेत्र में आप क्या बदलाव देखते हैं? (नई तकनीक, प्रतिस्पर्धा, मांग…)",
  storyPlaceholder:"कुछ ईमानदार वाक्य लिखें…",
  errLikert:"कृपया इस खंड के सभी कथनों का उत्तर दें।",
  errStories:"कृपया कम से कम एक विवरण भरें।",
  fromYourWords:"आपके अपने शब्दों में:",
  derivedNote:"ये निष्कर्ष आपके उत्तरों और विवरणों से स्वचालित रूप से निकाले गए हैं।",
  dvHelpHigh:"विशेषज्ञ पहचान — सहकर्मी सक्रिय रूप से आपकी सलाह लेते हैं।",
  dvHelpLow:"कम दृश्यता — आपकी विशेषज्ञता अभी सहकर्मियों में पहचानी नहीं गई है।",
  dvDeadlineHigh:"भरोसेमंद डिलीवरी — आप बिना निगरानी समयसीमा पूरी करते हैं।",
  dvDeadlineLow:"समय प्रबंधन — बाहरी दबाव के बिना समयसीमा खिसक जाती है।",
  dvPresentHigh:"आत्मविश्वासी संवादक — वरिष्ठों के सामने सहज।",
  dvPresentLow:"प्रस्तुति का आत्मविश्वास — वरिष्ठों से विचार साझा करना कठिन लगता है।",
  dvPostponeHigh:"टालमटोल — कठिन या अस्पष्ट कार्य टलते रहते हैं।",
  dvPostponeLow:"मज़बूत आत्म-अनुशासन — आप कठिन कार्यों से सीधे निपटते हैं।",
  dvLearnHigh:"तेज़ शिक्षार्थी — नए टूल साथियों से जल्दी सीखते हैं।",
  dvLearnLow:"सीखने की गति — नए टूल में अतिरिक्त समय लगता है।",
  dvNoHigh:"अति-प्रतिबद्धता — 'ना' न कह पाने से बोझ बढ़ता है।",
  dvNoLow:"स्वस्थ सीमाएँ — आप अपना कार्यभार सोच-समझकर रखते हैं।",
  dvGrowthHigh:"बढ़ता उद्योग आपके आसपास नई भूमिकाएँ बना रहा है।",
  dvGrowthLow:"ठहरा हुआ उद्योग आपके क्षेत्र में अवसर सीमित कर सकता है।",
  dvNetworkHigh:"टीम से बाहर का नेटवर्क अप्रत्याशित दरवाज़े खोल सकता है।",
  dvNetworkLow:"टीम के बाहर सीमित पेशेवर नेटवर्क।",
  dvAutoHigh:"ऑटोमेशन जोखिम — आपके नियमित काम का हिस्सा स्वचालित हो सकता है।",
  dvPaceHigh:"स्किल-गैप जोखिम — भूमिका की माँगें आपकी सीखने की गति से तेज़ हैं।",
  dvPaceLow:"आप अपनी भूमिका की बदलती माँगों के साथ कदम मिला रहे हैं।",
  dvTrainHigh:"आंतरिक प्रशिक्षण, मेंटरिंग और प्रोजेक्ट आपके लिए उपलब्ध हैं।",
  dvTrainLow:"आंतरिक विकास संसाधन कम — प्रगति आपकी अपनी पहल पर निर्भर है।",
  dvDefaultS:"निरंतर, भरोसेमंद दैनिक प्रदर्शन।",
  dvDefaultW:"कोई बड़ी कमज़ोरी सामने नहीं आई — अनदेखे पहलुओं से सतर्क रहें।",
  dvDefaultO:"हर उद्योग में AI टूल्स का बढ़ता उपयोग — इन्हें जल्दी सीखें।",
  dvDefaultT:"सामान्य बाज़ार बदलाव — अपनी स्किल्स ताज़ा रखें।",
  stepOf:"चरण {n} / {total}",
  stepProfile:"प्रोफ़ाइल", stepStrengths:"ताकतें", stepWeaknesses:"कमज़ोरियाँ", stepOpportunities:"अवसर", stepThreats:"खतरे",
  profileTitle:"अपनी भूमिका के बारे में बताएँ",
  roleLabel:"पद / भूमिका", rolePlaceholder:"जैसे प्रोडक्ट मैनेजर",
  industryLabel:"उद्योग", industryPlaceholder:"जैसे टेक्नोलॉजी, वित्त, स्वास्थ्य सेवा",
  smartAssistBtn:"स्मार्ट असिस्ट", smartAssistHint:"आपकी प्रोफ़ाइल के लिए उद्योग-मानक बेंचमार्क लाता है।",
  smartAssistLoading:"उद्योग बेंचमार्क का विश्लेषण हो रहा है…", smartAssistTitle:"आपकी प्रोफ़ाइल के लिए बेंचमार्क",
  saSkills:"अपेक्षित मुख्य कौशल", saTrends:"ध्यान देने योग्य रुझान",
  attachTitle:"दस्तावेज़ संलग्न करें (वैकल्पिक)", attachHint:"रिज़्यूमे, SOP या परफ़ॉर्मेंस रिव्यू — इसका संदर्भ आपके विश्लेषण में शामिल किया जाएगा।",
  attachBtn:"फ़ाइल चुनें", attachedMsg:"संलग्न: {file}",
  internalTag:"आंतरिक", externalTag:"बाहरी",
  sIntro:"जो आप पहले से अच्छा करते हैं।",
  sQ1:"सहकर्मी किन मुख्य कौशलों के लिए आप पर भरोसा करते हैं?", sQ2:"इस वर्ष की आपकी सबसे गर्व करने वाली उपलब्धि क्या है?", sQ3:"समान भूमिका वाले साथियों की तुलना में आपका अनोखा लाभ क्या है?",
  wIntro:"जहाँ आपके पास बढ़ने की गुंजाइश है।",
  wQ1:"कौन-सी कौशल की कमी आपको सबसे अधिक धीमा करती है?", wQ2:"आपके पास वर्तमान में किन संसाधनों या सहयोग की कमी है?", wQ3:"किन कार्यों को आप अक्सर टालते रहते हैं?",
  oIntro:"बाहरी संभावनाएँ जिन्हें आप अपना सकते हैं।",
  oQ1:"अगले 1–2 वर्षों में आप किस उद्योग रुझान का लाभ उठा सकते हैं?", oQ2:"कौन-से लोग या नेटवर्क आपके लिए नए द्वार खोल सकते हैं?", oQ3:"कौन-सी आगामी तकनीक या कौशल आपका मूल्य बढ़ाएगा?",
  tIntro:"बाहरी जोखिम जिनके लिए तैयारी ज़रूरी है।",
  tQ1:"आपके जॉब मार्केट में प्रतिस्पर्धा सबसे अधिक कहाँ है?", tQ2:"आपकी भूमिका के कौन-से हिस्से ऑटोमेशन या AI बदल सकते हैं?", tQ3:"आपकी भूमिका की आवश्यकताएँ कैसे बदल रही हैं?",
  moreDetails:"और विवरण जोड़ें (वैकल्पिक)", moreDetailsPlaceholder:"और कुछ जो विश्लेषण में शामिल करना चाहें…",
  nextBtn:"आगे", prevBtn:"पीछे", submitBtn:"मेरा विश्लेषण बनाएँ",
  errAnswerOne:"कृपया इस खंड में कम से कम एक प्रश्न का उत्तर दें।", errProfile:"कृपया अपनी भूमिका और उद्योग भरें।",
  toastSaved:"विश्लेषण सहेजा गया। बहुत बढ़िया!",
  dashTitle:"आपका व्यक्तिगत SWOT विश्लेषण",
  strengths:"ताकतें", weaknesses:"कमज़ोरियाँ", opportunities:"अवसर", threats:"खतरे",
  attachedContext:"“{file}” का संदर्भ इस विश्लेषण में शामिल किया गया।",
  growthTitle:"विकास मार्गदर्शिका और अगले कदम",
  roadmapTitle:"करियर रोडमैप और अपस्किलिंग गाइड",
  roadmapIntro:"आपकी भूमिका और उद्योग प्रोफ़ाइल के अनुसार चुना गया।",
  upskillTitle:"अभी विकसित करने योग्य कौशल",
  coursesTitle:"सुझाए गए कोर्स और प्रमाणपत्र",
  nextLevelTitle:"अगले स्तर पर कैसे बढ़ें",
  caseStudyTitle:"वास्तविक केस स्टडीज़",
  storyTitle:"वास्तविक प्रेरणा",
  takeawayLabel:"सीख",
  successionTitle:"करियर उत्तराधिकार पथ",
  successionIntro:"इस क्षेत्र की सामान्य भूमिका सीढ़ी, आपके पद के अनुसार।",
  youAreHereBadge:"आप यहाँ हैं",
  nextMoveLabel:"अगला सामान्य कदम",
  focusLabel:"फोकस",
  gSO:"उपयोग करें: ताकत → अवसर", gWO:"सुधारें: अवसर → कमज़ोरी", gST:"बचाव करें: ताकत बनाम खतरा", gWT:"कम करें: कमज़ोरी × खतरा",
  tplSO:"अपनी ताकत “{s}” को अवसर “{o}” के साथ जोड़ें। ऐसे कार्यों के लिए आगे आएँ जहाँ यह संयोजन निर्णयकर्ताओं को दिखे।",
  tplWO:"“{o}” को “{w}” पर काम करने का एक व्यवस्थित तरीका बनाएँ — नई और रोमांचक चीज़ से जुड़कर विकास बेहतर टिकता है।",
  tplST:"आपकी ताकत “{s}” “{t}” के खिलाफ आपका सबसे अच्छा बचाव है। इसे निखारते रहें और अपनी टीम से बाहर भी पहचान दिलाएँ।",
  tplWT:"“{w}” और “{t}” का मेल आपका सबसे बड़ा जोखिम क्षेत्र है। 90-दिन की सुधार योजना बनाएँ और अंतर पाटने के लिए मेंटर या कोर्स खोजें।",
  planTitle:"सुझाई गई 30/60/90-दिन की योजना",
  plan30:"दिन 1–30: अपनी ताकतों को दर्ज करें और एक स्पष्ट उपलब्धि अपने मैनेजर से साझा करें।",
  plan60:"दिन 31–60: अपनी सबसे बड़ी कमज़ोरी पर केंद्रित एक कोर्स या प्रोजेक्ट शुरू करें।",
  plan90:"दिन 61–90: किसी एक अवसर पर कदम उठाएँ — सर्टिफिकेशन, नेटवर्क या चुनौतीपूर्ण असाइनमेंट।",
  retakeBtn:"प्रश्नावली दोबारा भरें", downloadPdfBtn:"PDF डाउनलोड करें",
  adminTitle:"यूनिवर्सल एडमिन कंसोल", adminSubtitle:"टीम अवलोकन, उपयोगकर्ता प्रबंधन और समग्र विश्लेषण।",
  mUsers:"कुल उपयोगकर्ता", mCompleted:"पूर्ण विश्लेषण", mRate:"पूर्णता दर", mPending:"लंबित",
  themesTitle:"साझा विषय", themesStrengths:"टीम की प्रमुख ताकतें", themesThreats:"टीम के प्रमुख खतरे", themesEmpty:"अभी पर्याप्त डेटा नहीं है।",
  viewBtn:"देखें", backToConsole:"कंसोल पर वापस",
  vaTitle:"टीम SWOT विश्लेषण", vaSelectUser:"टीम सदस्य", vaNewest:"नवीनतम पहले", vaOldest:"पुराने पहले",
  vaCompletedOn:"{date} को पूर्ण", vaNone:"अभी कोई पूर्ण विश्लेषण नहीं।",
  usersTitle:"उपयोगकर्ता प्रबंधन",
  colName:"नाम", colEmail:"ईमेल", colCreated:"निर्मित", colStatus:"स्थिति", colActions:"कार्रवाइयाँ",
  statusDone:"पूर्ण", statusPending:"लंबित",
  addUserBtn:"नया उपयोगकर्ता जोड़ें", resetPwdBtn:"पासवर्ड रीसेट", deleteBtn:"हटाएँ", adminBadge:"एडमिन",
  confirmDeleteTitle:"उपयोगकर्ता हटाएँ?", confirmDelete:"{name} और उनका विश्लेषण हटाएँ? यह वापस नहीं होगा।",
  toastUserAdded:"उपयोगकर्ता {name} जोड़ा गया।", toastUserDeleted:"उपयोगकर्ता हटाया गया।", toastPwdReset:"पासवर्ड “{pwd}” पर रीसेट किया गया।",
  errUserExists:"इस ईमेल से उपयोगकर्ता पहले से मौजूद है।",
  modalAddTitle:"नया उपयोगकर्ता जोड़ें", modalRole:"भूमिका", roleUser:"उपयोगकर्ता", roleAdmin:"एडमिन", modalDefaultPwd:"प्रारंभिक पासवर्ड",
  saveBtn:"सहेजें", cancelBtn:"रद्द करें", confirmBtn:"हटाएँ", emptyAnswer:"—"
},
kn: {
  tagline:"ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಬೆಳವಣಿಗೆ, ನಕ್ಷೆಯಲ್ಲಿ.", signOut:"ಸೈನ್ ಔಟ್",
  navAdmin:"ಅಡ್ಮಿನ್ ಕನ್ಸೋಲ್", navMySwot:"ನನ್ನ SWOT",
  authTitle:"ಸ್ವಾಗತ", authSubtitle:"ವೃತ್ತಿಪರವಾಗಿ ಚಿಂತಿಸಲು, ಯೋಜಿಸಲು ಮತ್ತು ಬೆಳೆಯಲು ನಿಮ್ಮ ಖಾಸಗಿ ಸ್ಥಳ.",
  emailLabel:"ಇಮೇಲ್ ವಿಳಾಸ", emailPlaceholder:"you@company.com", continueBtn:"ಮುಂದುವರಿಸಿ",
  newUserNotice:"ನೀವು ಇಲ್ಲಿ ಹೊಸಬರು — ಖಾತೆ ರಚಿಸಲು ನಿಮ್ಮ ಪಾಸ್‌ವರ್ಡ್ ಹೊಂದಿಸಿ.",
  returningNotice:"ಮತ್ತೆ ಸ್ವಾಗತ! ಸೈನ್ ಇನ್ ಮಾಡಲು ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ.",
  nameLabel:"ಪೂರ್ಣ ಹೆಸರು", namePlaceholder:"ಉದಾ: ಪ್ರಿಯಾ ಶರ್ಮಾ",
  passwordLabel:"ಪಾಸ್‌ವರ್ಡ್", confirmPasswordLabel:"ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ",
  createAccountBtn:"ಖಾತೆ ರಚಿಸಿ", signInBtn:"ಸೈನ್ ಇನ್", backBtn:"ಹಿಂದೆ",
  demoHint:"ಡೆಮೊ ಅಡ್ಮಿನ್: admin@cakewala.in · ಪಾಸ್‌ವರ್ಡ್: admin123",
  errEmail:"ದಯವಿಟ್ಟು ಮಾನ್ಯ ಇಮೇಲ್ ವಿಳಾಸ ನಮೂದಿಸಿ.", errName:"ದಯವಿಟ್ಟು ನಿಮ್ಮ ಹೆಸರು ನಮೂದಿಸಿ.",
  errPasswordShort:"ಪಾಸ್‌ವರ್ಡ್ ಕನಿಷ್ಠ 6 ಅಕ್ಷರಗಳಿರಬೇಕು.", errPasswordMismatch:"ಪಾಸ್‌ವರ್ಡ್‌ಗಳು ಹೊಂದಿಕೆಯಾಗುತ್ತಿಲ್ಲ.",
  errWrongPassword:"ತಪ್ಪು ಪಾಸ್‌ವರ್ಡ್. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
  toastWelcome:"ಮತ್ತೆ ಸ್ವಾಗತ, {name}!", toastAccountCreated:"ಖಾತೆ ರಚಿಸಲಾಗಿದೆ. ಸ್ವಾಗತ, {name}!",
  qTitle:"ಸ್ಮಾರ್ಟ್ SWOT ಪ್ರಶ್ನಾವಳಿ", qIntro:"ನಿಮ್ಮ SWOT ನಿಮಗೆ ತಿಳಿದಿರಬೇಕಿಲ್ಲ — ಸರಳವಾಗಿ, ಪ್ರಾಮಾಣಿಕವಾಗಿ ಉತ್ತರಿಸಿ. ನಿಮ್ಮ ಉತ್ತರಗಳಿಂದ ಪ್ರೋಗ್ರಾಂ ಅದನ್ನು ರೂಪಿಸುತ್ತದೆ.",
  stepWork:"ಕೆಲಸದ ಶೈಲಿ", stepStories:"ನಿಮ್ಮ ಅನುಭವಗಳು", stepEnv:"ನಿಮ್ಮ ಪರಿಸರ",
  workIntro:"ಪ್ರತಿ ಹೇಳಿಕೆ ನಿಮಗೆ ಎಷ್ಟು ಹೊಂದುತ್ತದೆ ಎಂದು ಗುರುತಿಸಿ. ಸರಿ-ತಪ್ಪು ಉತ್ತರಗಳಿಲ್ಲ.",
  storiesIntro:"ನಿಮ್ಮ ಮಾತಿನಲ್ಲಿ ಬರೆಯಿರಿ — ನಿಮ್ಮ ವಿವರಣೆಗಳಿಂದ ಪ್ರೋಗ್ರಾಂ ನಿಮ್ಮ ಸಾಮರ್ಥ್ಯ ಮತ್ತು ದೌರ್ಬಲ್ಯಗಳನ್ನು ಕಂಡುಹಿಡಿಯುತ್ತದೆ.",
  envIntro:"ಈಗ ನಿಮ್ಮ ಪಾತ್ರದ ಸುತ್ತಲಿನ ಜಗತ್ತಿನ ಬಗ್ಗೆ ಕೆಲವು ಹೇಳಿಕೆಗಳು.",
  scaleLow:"ಖಂಡಿತ ಒಪ್ಪುವುದಿಲ್ಲ", scaleHigh:"ಸಂಪೂರ್ಣ ಒಪ್ಪುತ್ತೇನೆ",
  lkHelp:"ಸಹೋದ್ಯೋಗಿಗಳು ನನ್ನ ಕ್ಷೇತ್ರದಲ್ಲಿ ಸಹಾಯ ಅಥವಾ ಸಲಹೆಗಾಗಿ ಆಗಾಗ ನನ್ನ ಬಳಿ ಬರುತ್ತಾರೆ.",
  lkDeadline:"ನೆನಪಿಸದೆಯೂ ನಾನು ಕೆಲಸವನ್ನು ಗಡುವಿನೊಳಗೆ ಅಥವಾ ಮೊದಲೇ ಮುಗಿಸುತ್ತೇನೆ.",
  lkPresent:"ಹಿರಿಯರ ಅಥವಾ ಗುಂಪಿನ ಮುಂದೆ ನನ್ನ ವಿಚಾರ ಮಂಡಿಸಲು ನನಗೆ ಆತ್ಮವಿಶ್ವಾಸವಿದೆ.",
  lkPostpone:"ಕಷ್ಟ, ಅಸ್ಪಷ್ಟ ಅಥವಾ ಬೇಸರದ ಕೆಲಸಗಳನ್ನು ನಾನು ಆಗಾಗ ಮುಂದೂಡುತ್ತೇನೆ.",
  lkLearn:"ಹೊಸ ಟೂಲ್‌ಗಳು ಮತ್ತು ವಿಧಾನಗಳನ್ನು ನನ್ನ ಸಹವರ್ತಿಗಳಿಗಿಂತ ಬೇಗ ಕಲಿಯುತ್ತೇನೆ.",
  lkNo:"'ಇಲ್ಲ' ಎನ್ನುವುದು ನನಗೆ ಕಷ್ಟ, ಹಾಗಾಗಿ ಹೆಚ್ಚು ಕೆಲಸ ಹೊತ್ತುಕೊಳ್ಳುತ್ತೇನೆ.",
  lkGrowth:"ನನ್ನ ಉದ್ಯಮ ಬೆಳೆಯುತ್ತಿದ್ದು ಹೊಸ ರೀತಿಯ ಹುದ್ದೆಗಳು ಸೃಷ್ಟಿಯಾಗುತ್ತಿವೆ.",
  lkNetwork:"ನನ್ನ ವೃತ್ತಿಜೀವನಕ್ಕೆ ನೆರವಾಗಬಲ್ಲ ತಂಡದ ಹೊರಗಿನವರೊಂದಿಗೆ ನಿಯಮಿತವಾಗಿ ಮಾತನಾಡುತ್ತೇನೆ.",
  lkAuto:"ನನ್ನ ದೈನಂದಿನ ಕೆಲಸದ ದೊಡ್ಡ ಭಾಗವನ್ನು ಸಾಫ್ಟ್‌ವೇರ್ ಅಥವಾ AI ಮಾಡಬಹುದು.",
  lkPace:"ನನ್ನ ಪಾತ್ರಕ್ಕೆ ಬೇಕಾದ ಕೌಶಲ್ಯಗಳು ನಾನು ಕಲಿಯುವುದಕ್ಕಿಂತ ವೇಗವಾಗಿ ಬದಲಾಗುತ್ತಿವೆ.",
  lkTrain:"ನನ್ನ ಸಂಸ್ಥೆ ತರಬೇತಿ, ಮಾರ್ಗದರ್ಶನ ಅಥವಾ ಸೇರಬಹುದಾದ ಪ್ರಾಜೆಕ್ಟ್‌ಗಳನ್ನು ನೀಡುತ್ತದೆ.",
  tpProud:"ಇತ್ತೀಚೆಗೆ ನಿಮಗೆ ಹೆಮ್ಮೆ ತಂದ ಒಂದು ಕೆಲಸ ವಿವರಿಸಿ. ನೀವು ನಿಖರವಾಗಿ ಏನು ಚೆನ್ನಾಗಿ ಮಾಡಿದಿರಿ?",
  tpDrain:"ಯಾವ ಕೆಲಸವನ್ನು ನೀವು ಮುಂದೂಡುತ್ತಲೇ ಇರುತ್ತೀರಿ ಅಥವಾ ಯಾವುದು ಹೆಚ್ಚು ದಣಿಸುತ್ತದೆ? ಅದು ಏಕೆ ಕಷ್ಟ?",
  tpFeedback:"ನಿಮ್ಮ ಬಗ್ಗೆ — ಹೊಗಳಿಕೆ ಅಥವಾ ಟೀಕೆ — ಕೆಲಸದಲ್ಲಿ ಒಂದಕ್ಕಿಂತ ಹೆಚ್ಚು ಬಾರಿ ಕೇಳಿದ ಮಾತು ಯಾವುದು?",
  tpFuture:"ಮುಂದಿನ 2–3 ವರ್ಷಗಳಲ್ಲಿ ನಿಮ್ಮ ಕ್ಷೇತ್ರದಲ್ಲಿ ಯಾವ ಬದಲಾವಣೆಗಳನ್ನು ನಿರೀಕ್ಷಿಸುತ್ತೀರಿ? (ಹೊಸ ತಂತ್ರಜ್ಞಾನ, ಸ್ಪರ್ಧೆ, ಬೇಡಿಕೆ…)",
  storyPlaceholder:"ಕೆಲವು ಪ್ರಾಮಾಣಿಕ ವಾಕ್ಯಗಳನ್ನು ಬರೆಯಿರಿ…",
  errLikert:"ದಯವಿಟ್ಟು ಈ ವಿಭಾಗದ ಎಲ್ಲಾ ಹೇಳಿಕೆಗಳಿಗೆ ಉತ್ತರಿಸಿ.",
  errStories:"ದಯವಿಟ್ಟು ಕನಿಷ್ಠ ಒಂದು ವಿವರಣೆ ಭರ್ತಿ ಮಾಡಿ.",
  fromYourWords:"ನಿಮ್ಮದೇ ಮಾತಿನಲ್ಲಿ:",
  derivedNote:"ಈ ಒಳನೋಟಗಳನ್ನು ನಿಮ್ಮ ಉತ್ತರ ಮತ್ತು ವಿವರಣೆಗಳಿಂದ ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಪಡೆಯಲಾಗಿದೆ.",
  dvHelpHigh:"ಪರಿಣತರ ಗುರುತು — ಸಹೋದ್ಯೋಗಿಗಳು ಸಕ್ರಿಯವಾಗಿ ನಿಮ್ಮ ಸಲಹೆ ಬಯಸುತ್ತಾರೆ.",
  dvHelpLow:"ಕಡಿಮೆ ಗೋಚರತೆ — ನಿಮ್ಮ ಪರಿಣತಿ ಇನ್ನೂ ಸಹೋದ್ಯೋಗಿಗಳಲ್ಲಿ ಗುರುತಿಸಲ್ಪಟ್ಟಿಲ್ಲ.",
  dvDeadlineHigh:"ವಿಶ್ವಾಸಾರ್ಹ ವಿತರಣೆ — ಮೇಲ್ವಿಚಾರಣೆ ಇಲ್ಲದೆ ಗಡುವು ಪಾಲಿಸುತ್ತೀರಿ.",
  dvDeadlineLow:"ಸಮಯ ನಿರ್ವಹಣೆ — ಬಾಹ್ಯ ಒತ್ತಡವಿಲ್ಲದೆ ಗಡುವು ಜಾರುತ್ತದೆ.",
  dvPresentHigh:"ಆತ್ಮವಿಶ್ವಾಸದ ಸಂವಹನಕಾರ — ಹಿರಿಯರ ಮುಂದೆಯೂ ಸಹಜ.",
  dvPresentLow:"ಮಂಡನೆಯ ಆತ್ಮವಿಶ್ವಾಸ — ಹಿರಿಯರ ಮುಂದೆ ವಿಚಾರ ಹಂಚುವುದು ಕಷ್ಟ.",
  dvPostponeHigh:"ಮುಂದೂಡುವಿಕೆ — ಕಷ್ಟದ ಅಥವಾ ಅಸ್ಪಷ್ಟ ಕೆಲಸಗಳು ಮುಂದೆ ಹೋಗುತ್ತಲೇ ಇರುತ್ತವೆ.",
  dvPostponeLow:"ಗಟ್ಟಿ ಸ್ವಯಂ-ಶಿಸ್ತು — ಕಷ್ಟದ ಕೆಲಸಗಳನ್ನು ನೇರವಾಗಿ ಎದುರಿಸುತ್ತೀರಿ.",
  dvLearnHigh:"ವೇಗದ ಕಲಿಕೆ — ಹೊಸ ಟೂಲ್‌ಗಳನ್ನು ಸಹವರ್ತಿಗಳಿಗಿಂತ ಬೇಗ ಹೀರಿಕೊಳ್ಳುತ್ತೀರಿ.",
  dvLearnLow:"ಕಲಿಕೆಯ ವೇಗ — ಹೊಸ ಟೂಲ್‌ಗಳಿಗೆ ಹೆಚ್ಚು ಸಮಯ ಬೇಕಾಗುತ್ತದೆ.",
  dvNoHigh:"ಅತಿ ಬದ್ಧತೆ — 'ಇಲ್ಲ' ಎನ್ನಲಾಗದೆ ಹೊರೆ ಹೆಚ್ಚುತ್ತದೆ.",
  dvNoLow:"ಆರೋಗ್ಯಕರ ಮಿತಿಗಳು — ಕೆಲಸದ ಹೊರೆಯನ್ನು ಯೋಜಿತವಾಗಿ ನಿರ್ವಹಿಸುತ್ತೀರಿ.",
  dvGrowthHigh:"ಬೆಳೆಯುತ್ತಿರುವ ಉದ್ಯಮ ನಿಮ್ಮ ಸುತ್ತ ಹೊಸ ಹುದ್ದೆಗಳನ್ನು ಸೃಷ್ಟಿಸುತ್ತಿದೆ.",
  dvGrowthLow:"ನಿಂತ ಉದ್ಯಮ ನಿಮ್ಮ ಕ್ಷೇತ್ರದ ಅವಕಾಶಗಳನ್ನು ಸೀಮಿತಗೊಳಿಸಬಹುದು.",
  dvNetworkHigh:"ತಂಡದ ಹೊರಗಿನ ನೆಟ್‌ವರ್ಕ್ ಅನಿರೀಕ್ಷಿತ ಬಾಗಿಲುಗಳನ್ನು ತೆರೆಯಬಹುದು.",
  dvNetworkLow:"ತಂಡದ ಹೊರಗೆ ಸೀಮಿತ ವೃತ್ತಿಪರ ನೆಟ್‌ವರ್ಕ್.",
  dvAutoHigh:"ಆಟೊಮೇಷನ್ ಅಪಾಯ — ನಿಮ್ಮ ದಿನಚರಿ ಕೆಲಸದ ಭಾಗ ಸ್ವಯಂಚಾಲಿತವಾಗಬಹುದು.",
  dvPaceHigh:"ಕೌಶಲ್ಯ-ಅಂತರದ ಅಪಾಯ — ಬೇಡಿಕೆಗಳು ನಿಮ್ಮ ಕಲಿಕೆಗಿಂತ ವೇಗವಾಗಿವೆ.",
  dvPaceLow:"ಪಾತ್ರದ ಬದಲಾಗುವ ಬೇಡಿಕೆಗಳೊಂದಿಗೆ ಹೆಜ್ಜೆ ಹಾಕುತ್ತಿದ್ದೀರಿ.",
  dvTrainHigh:"ಆಂತರಿಕ ತರಬೇತಿ, ಮಾರ್ಗದರ್ಶನ ಮತ್ತು ಪ್ರಾಜೆಕ್ಟ್‌ಗಳು ನಿಮಗಾಗಿ ಲಭ್ಯ.",
  dvTrainLow:"ಆಂತರಿಕ ಬೆಳವಣಿಗೆ ಸಂಪನ್ಮೂಲ ಕಡಿಮೆ — ಪ್ರಗತಿ ನಿಮ್ಮ ಸ್ವಂತ ಪ್ರಯತ್ನದ ಮೇಲೆ.",
  dvDefaultS:"ಸ್ಥಿರ, ವಿಶ್ವಾಸಾರ್ಹ ದೈನಂದಿನ ಕಾರ್ಯಕ್ಷಮತೆ.",
  dvDefaultW:"ದೊಡ್ಡ ದೌರ್ಬಲ್ಯ ಕಾಣಲಿಲ್ಲ — ಕಾಣದ ಮೂಲೆಗಳ ಬಗ್ಗೆ ಎಚ್ಚರವಿರಲಿ.",
  dvDefaultO:"ಎಲ್ಲ ಉದ್ಯಮಗಳಲ್ಲಿ AI ಟೂಲ್‌ಗಳ ಬಳಕೆ ಹೆಚ್ಚುತ್ತಿದೆ — ಬೇಗ ಕಲಿಯಿರಿ.",
  dvDefaultT:"ಸಾಮಾನ್ಯ ಮಾರುಕಟ್ಟೆ ಬದಲಾವಣೆ — ಕೌಶಲ್ಯ ನವೀಕೃತವಾಗಿಡಿ.",
  stepOf:"ಹಂತ {n} / {total}",
  stepProfile:"ಪ್ರೊಫೈಲ್", stepStrengths:"ಸಾಮರ್ಥ್ಯಗಳು", stepWeaknesses:"ದೌರ್ಬಲ್ಯಗಳು", stepOpportunities:"ಅವಕಾಶಗಳು", stepThreats:"ಬೆದರಿಕೆಗಳು",
  profileTitle:"ನಿಮ್ಮ ಪಾತ್ರದ ಬಗ್ಗೆ ತಿಳಿಸಿ",
  roleLabel:"ಹುದ್ದೆ / ಪಾತ್ರ", rolePlaceholder:"ಉದಾ: ಪ್ರಾಡಕ್ಟ್ ಮ್ಯಾನೇಜರ್",
  industryLabel:"ಉದ್ಯಮ", industryPlaceholder:"ಉದಾ: ತಂತ್ರಜ್ಞಾನ, ಹಣಕಾಸು, ಆರೋಗ್ಯ",
  smartAssistBtn:"ಸ್ಮಾರ್ಟ್ ಅಸಿಸ್ಟ್", smartAssistHint:"ನಿಮ್ಮ ಪ್ರೊಫೈಲ್‌ಗೆ ಉದ್ಯಮ-ಮಾನದಂಡ ಬೆಂಚ್‌ಮಾರ್ಕ್‌ಗಳನ್ನು ತರುತ್ತದೆ.",
  smartAssistLoading:"ಉದ್ಯಮ ಬೆಂಚ್‌ಮಾರ್ಕ್‌ಗಳ ವಿಶ್ಲೇಷಣೆ ನಡೆಯುತ್ತಿದೆ…", smartAssistTitle:"ನಿಮ್ಮ ಪ್ರೊಫೈಲ್‌ಗೆ ಬೆಂಚ್‌ಮಾರ್ಕ್‌ಗಳು",
  saSkills:"ನಿರೀಕ್ಷಿತ ಪ್ರಮುಖ ಕೌಶಲ್ಯಗಳು", saTrends:"ಗಮನಿಸಬೇಕಾದ ಪ್ರವೃತ್ತಿಗಳು",
  attachTitle:"ದಾಖಲೆ ಲಗತ್ತಿಸಿ (ಐಚ್ಛಿಕ)", attachHint:"ರೆಸ್ಯೂಮೆ, SOP ಅಥವಾ ಕಾರ್ಯಕ್ಷಮತೆ ವರದಿ — ಅದರ ಸಂದರ್ಭವನ್ನು ವಿಶ್ಲೇಷಣೆಯಲ್ಲಿ ಸೇರಿಸಲಾಗುವುದು.",
  attachBtn:"ಫೈಲ್ ಆಯ್ಕೆಮಾಡಿ", attachedMsg:"ಲಗತ್ತಿಸಲಾಗಿದೆ: {file}",
  internalTag:"ಆಂತರಿಕ", externalTag:"ಬಾಹ್ಯ",
  sIntro:"ನೀವು ಈಗಾಗಲೇ ಚೆನ್ನಾಗಿ ಮಾಡುವ ಸಂಗತಿಗಳು.",
  sQ1:"ಸಹೋದ್ಯೋಗಿಗಳು ಯಾವ ಪ್ರಮುಖ ಕೌಶಲ್ಯಗಳಿಗಾಗಿ ನಿಮ್ಮನ್ನು ಅವಲಂಬಿಸುತ್ತಾರೆ?", sQ2:"ಈ ವರ್ಷ ನಿಮಗೆ ಅತ್ಯಂತ ಹೆಮ್ಮೆಯ ಸಾಧನೆ ಯಾವುದು?", sQ3:"ಸಮಾನ ಹುದ್ದೆಯ ಸಹವರ್ತಿಗಳಿಗಿಂತ ನಿಮ್ಮ ವಿಶೇಷ ಅನುಕೂಲ ಏನು?",
  wIntro:"ನೀವು ಬೆಳೆಯಬಹುದಾದ ಕ್ಷೇತ್ರಗಳು.",
  wQ1:"ಯಾವ ಕೌಶಲ್ಯದ ಕೊರತೆ ನಿಮ್ಮನ್ನು ಹೆಚ್ಚು ನಿಧಾನಗೊಳಿಸುತ್ತದೆ?", wQ2:"ಸದ್ಯ ನಿಮಗೆ ಯಾವ ಸಂಪನ್ಮೂಲ ಅಥವಾ ಬೆಂಬಲದ ಕೊರತೆಯಿದೆ?", wQ3:"ಯಾವ ಕೆಲಸಗಳನ್ನು ನೀವು ಮುಂದೂಡುತ್ತೀರಿ?",
  oIntro:"ನೀವು ಬಳಸಿಕೊಳ್ಳಬಹುದಾದ ಬಾಹ್ಯ ಸಾಧ್ಯತೆಗಳು.",
  oQ1:"ಮುಂದಿನ 1–2 ವರ್ಷಗಳಲ್ಲಿ ಯಾವ ಉದ್ಯಮ ಪ್ರವೃತ್ತಿಯ ಲಾಭ ಪಡೆಯಬಹುದು?", oQ2:"ಯಾವ ವ್ಯಕ್ತಿಗಳು ಅಥವಾ ನೆಟ್‌ವರ್ಕ್‌ಗಳು ನಿಮಗೆ ಹೊಸ ಬಾಗಿಲು ತೆರೆಯಬಹುದು?", oQ3:"ಯಾವ ಹೊಸ ತಂತ್ರಜ್ಞಾನ ಅಥವಾ ಕೌಶಲ್ಯ ನಿಮ್ಮ ಮೌಲ್ಯ ಹೆಚ್ಚಿಸುತ್ತದೆ?",
  tIntro:"ಸಿದ್ಧತೆ ಅಗತ್ಯವಿರುವ ಬಾಹ್ಯ ಅಪಾಯಗಳು.",
  tQ1:"ನಿಮ್ಮ ಉದ್ಯೋಗ ಮಾರುಕಟ್ಟೆಯಲ್ಲಿ ಸ್ಪರ್ಧೆ ಎಲ್ಲಿ ಹೆಚ್ಚು?", tQ2:"ನಿಮ್ಮ ಪಾತ್ರದ ಯಾವ ಭಾಗಗಳನ್ನು ಆಟೊಮೇಷನ್ ಅಥವಾ AI ಬದಲಾಯಿಸಬಹುದು?", tQ3:"ನಿಮ್ಮ ಪಾತ್ರದ ಅವಶ್ಯಕತೆಗಳು ಹೇಗೆ ಬದಲಾಗುತ್ತಿವೆ?",
  moreDetails:"ಹೆಚ್ಚಿನ ವಿವರ ಸೇರಿಸಿ (ಐಚ್ಛಿಕ)", moreDetailsPlaceholder:"ವಿಶ್ಲೇಷಣೆಯಲ್ಲಿ ಪರಿಗಣಿಸಬೇಕಾದ ಇನ್ನೇನಾದರೂ…",
  nextBtn:"ಮುಂದೆ", prevBtn:"ಹಿಂದೆ", submitBtn:"ನನ್ನ ವಿಶ್ಲೇಷಣೆ ರಚಿಸಿ",
  errAnswerOne:"ಈ ವಿಭಾಗದಲ್ಲಿ ಕನಿಷ್ಠ ಒಂದು ಪ್ರಶ್ನೆಗೆ ಉತ್ತರಿಸಿ.", errProfile:"ದಯವಿಟ್ಟು ನಿಮ್ಮ ಪಾತ್ರ ಮತ್ತು ಉದ್ಯಮವನ್ನು ಭರ್ತಿ ಮಾಡಿ.",
  toastSaved:"ವಿಶ್ಲೇಷಣೆ ಉಳಿಸಲಾಗಿದೆ. ಅದ್ಭುತ!",
  dashTitle:"ನಿಮ್ಮ ವೈಯಕ್ತಿಕ SWOT ವಿಶ್ಲೇಷಣೆ",
  strengths:"ಸಾಮರ್ಥ್ಯಗಳು", weaknesses:"ದೌರ್ಬಲ್ಯಗಳು", opportunities:"ಅವಕಾಶಗಳು", threats:"ಬೆದರಿಕೆಗಳು",
  attachedContext:"“{file}” ನ ಸಂದರ್ಭವನ್ನು ಈ ವಿಶ್ಲೇಷಣೆಯಲ್ಲಿ ಸೇರಿಸಲಾಗಿದೆ.",
  growthTitle:"ಬೆಳವಣಿಗೆ ಮಾರ್ಗದರ್ಶಿ ಮತ್ತು ಮುಂದಿನ ಹೆಜ್ಜೆಗಳು",
  roadmapTitle:"ವೃತ್ತಿ ಮಾರ್ಗಸೂಚಿ ಮತ್ತು ಕೌಶಲ್ಯ ಮಾರ್ಗದರ್ಶಿ",
  roadmapIntro:"ನಿಮ್ಮ ಪಾತ್ರ ಮತ್ತು ಉದ್ಯಮ ಪ್ರೊಫೈಲ್‌ಗೆ ಹೊಂದಿಸಲಾಗಿದೆ.",
  upskillTitle:"ಈಗ ಬೆಳೆಸಬೇಕಾದ ಕೌಶಲ್ಯಗಳು",
  coursesTitle:"ಶಿಫಾರಸು ಮಾಡಿದ ಕೋರ್ಸ್ ಮತ್ತು ಪ್ರಮಾಣಪತ್ರಗಳು",
  nextLevelTitle:"ಮುಂದಿನ ಹಂತಕ್ಕೆ ಹೋಗುವುದು ಹೇಗೆ",
  caseStudyTitle:"ನೈಜ ಜಗತ್ತಿನ ಕೇಸ್ ಸ್ಟಡಿಗಳು",
  storyTitle:"ನೈಜ ಪ್ರೇರಣೆ",
  takeawayLabel:"ಪಾಠ",
  successionTitle:"ವೃತ್ತಿ ಉತ್ತರಾಧಿಕಾರ ಮಾರ್ಗ",
  successionIntro:"ಈ ಕ್ಷೇತ್ರದ ಸಾಮಾನ್ಯ ಪಾತ್ರ ಏಣಿ, ನಿಮ್ಮ ಹುದ್ದೆಗೆ ಹೊಂದಿಸಲಾಗಿದೆ.",
  youAreHereBadge:"ನೀವು ಇಲ್ಲಿದ್ದೀರಿ",
  nextMoveLabel:"ಸಾಮಾನ್ಯ ಮುಂದಿನ ಹೆಜ್ಜೆ",
  focusLabel:"ಗಮನ",
  gSO:"ಬಳಸಿ: ಸಾಮರ್ಥ್ಯ → ಅವಕಾಶ", gWO:"ಸುಧಾರಿಸಿ: ಅವಕಾಶ → ದೌರ್ಬಲ್ಯ", gST:"ರಕ್ಷಿಸಿ: ಸಾಮರ್ಥ್ಯ vs ಬೆದರಿಕೆ", gWT:"ತಗ್ಗಿಸಿ: ದೌರ್ಬಲ್ಯ × ಬೆದರಿಕೆ",
  tplSO:"ನಿಮ್ಮ ಸಾಮರ್ಥ್ಯ “{s}” ಅನ್ನು ಅವಕಾಶ “{o}” ದೊಂದಿಗೆ ಜೋಡಿಸಿ. ಈ ಸಂಯೋಜನೆ ನಿರ್ಣಯಕಾರರಿಗೆ ಕಾಣುವ ಕೆಲಸಗಳಿಗೆ ಮುಂದಾಗಿ.",
  tplWO:"“{w}” ಮೇಲೆ ಕೆಲಸ ಮಾಡಲು “{o}” ಅನ್ನು ವ್ಯವಸ್ಥಿತ ಮಾರ್ಗವಾಗಿ ಬಳಸಿ — ಹೊಸತಕ್ಕೆ ಜೋಡಿಸಿದ ಬೆಳವಣಿಗೆ ಹೆಚ್ಚು ಬಾಳುತ್ತದೆ.",
  tplST:"“{t}” ವಿರುದ್ಧ ನಿಮ್ಮ ಸಾಮರ್ಥ್ಯ “{s}” ಅತ್ಯುತ್ತಮ ರಕ್ಷಣೆ. ಅದನ್ನು ಹರಿತವಾಗಿಡಿ ಮತ್ತು ತಂಡದ ಹೊರಗೂ ಗುರುತಿಸುವಂತೆ ಮಾಡಿ.",
  tplWT:"“{w}” ಮತ್ತು “{t}” ಸೇರಿದರೆ ಅದು ನಿಮ್ಮ ಅತಿ ದೊಡ್ಡ ಅಪಾಯ ವಲಯ. 90-ದಿನಗಳ ಸುಧಾರಣಾ ಯೋಜನೆ ರೂಪಿಸಿ, ಮಾರ್ಗದರ್ಶಕ ಅಥವಾ ಕೋರ್ಸ್ ಹುಡುಕಿ.",
  planTitle:"ಸೂಚಿತ 30/60/90-ದಿನಗಳ ಯೋಜನೆ",
  plan30:"ದಿನ 1–30: ನಿಮ್ಮ ಸಾಮರ್ಥ್ಯಗಳನ್ನು ದಾಖಲಿಸಿ ಮತ್ತು ಒಂದು ಸ್ಪಷ್ಟ ಗೆಲುವನ್ನು ಮ್ಯಾನೇಜರ್‌ಗೆ ಹಂಚಿಕೊಳ್ಳಿ.",
  plan60:"ದಿನ 31–60: ನಿಮ್ಮ ದೊಡ್ಡ ದೌರ್ಬಲ್ಯವನ್ನು ಗುರಿಯಾಗಿಸುವ ಕೋರ್ಸ್ ಅಥವಾ ಪ್ರಾಜೆಕ್ಟ್ ಆರಂಭಿಸಿ.",
  plan90:"ದಿನ 61–90: ಒಂದು ಅವಕಾಶದ ಮೇಲೆ ಕ್ರಮ ಕೈಗೊಳ್ಳಿ — ಪ್ರಮಾಣೀಕರಣ, ನೆಟ್‌ವರ್ಕ್ ಅಥವಾ ಸವಾಲಿನ ಕೆಲಸ.",
  retakeBtn:"ಪ್ರಶ್ನಾವಳಿ ಮತ್ತೆ ಭರ್ತಿ ಮಾಡಿ", downloadPdfBtn:"PDF ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
  adminTitle:"ಯುನಿವರ್ಸల್ ಅಡ್ಮಿನ್ ಕನ್ಸೋಲ್", adminSubtitle:"ತಂಡದ ಅವಲೋಕನ, ಬಳಕೆದಾರ ನಿರ್ವಹಣೆ ಮತ್ತು ಸಮಗ್ರ ಒಳನೋಟಗಳು.",
  mUsers:"ಒಟ್ಟು ಬಳಕೆದಾರರು", mCompleted:"ಪೂರ್ಣಗೊಂಡ ವಿಶ್ಲೇಷಣೆಗಳು", mRate:"ಪೂರ್ಣತೆಯ ದರ", mPending:"ಬಾಕಿ",
  themesTitle:"ಸಾಮಾನ್ಯ ವಿಷಯಗಳು", themesStrengths:"ತಂಡದ ಪ್ರಮುಖ ಸಾಮರ್ಥ್ಯಗಳು", themesThreats:"ತಂಡದ ಪ್ರಮುಖ ಬೆದರಿಕೆಗಳು", themesEmpty:"ಸಾಕಷ್ಟು ಡೇಟಾ ಇನ್ನೂ ಇಲ್ಲ.",
  viewBtn:"ವೀಕ್ಷಿಸಿ", backToConsole:"ಕನ್ಸೋಲ್‌ಗೆ ಹಿಂದೆ",
  vaTitle:"ತಂಡದ SWOT ವಿಶ್ಲೇಷಣೆ", vaSelectUser:"ತಂಡದ ಸದಸ್ಯ", vaNewest:"ಹೊಸದು ಮೊದಲು", vaOldest:"ಹಳೆಯದು ಮೊದಲು",
  vaCompletedOn:"{date} ರಂದು ಪೂರ್ಣಗೊಂಡಿದೆ", vaNone:"ಇನ್ನೂ ಯಾವುದೇ ಪೂರ್ಣ ವಿಶ್ಲೇಷಣೆ ಇಲ್ಲ.",
  usersTitle:"ಬಳಕೆದಾರ ನಿರ್ವಹಣೆ",
  colName:"ಹೆಸರು", colEmail:"ಇಮೇಲ್", colCreated:"ರಚಿಸಿದ ದಿನಾಂಕ", colStatus:"ಸ್ಥಿತಿ", colActions:"ಕ್ರಿಯೆಗಳು",
  statusDone:"ಪೂರ್ಣ", statusPending:"ಬಾಕಿ",
  addUserBtn:"ಹೊಸ ಬಳಕೆದಾರ ಸೇರಿಸಿ", resetPwdBtn:"ಪಾಸ್‌ವರ್ಡ್ ರೀಸೆಟ್", deleteBtn:"ಅಳಿಸಿ", adminBadge:"ಅಡ್ಮಿನ್",
  confirmDeleteTitle:"ಬಳಕೆದಾರರನ್ನು ಅಳಿಸುವುದೇ?", confirmDelete:"{name} ಮತ್ತು ಅವರ ವಿಶ್ಲೇಷಣೆಯನ್ನು ಅಳಿಸುವುದೇ? ಇದನ್ನು ಹಿಂತಿರುಗಿಸಲಾಗದು.",
  toastUserAdded:"ಬಳಕೆದಾರ {name} ಸೇರಿಸಲಾಗಿದೆ.", toastUserDeleted:"ಬಳಕೆದಾರರನ್ನು ಅಳಿಸಲಾಗಿದೆ.", toastPwdReset:"ಪಾಸ್‌ವರ್ಡ್ “{pwd}” ಗೆ ರೀಸೆಟ್ ಮಾಡಲಾಗಿದೆ.",
  errUserExists:"ಈ ಇಮೇಲ್‌ನೊಂದಿಗೆ ಬಳಕೆದಾರ ಈಗಾಗಲೇ ಇದ್ದಾರೆ.",
  modalAddTitle:"ಹೊಸ ಬಳಕೆದಾರ ಸೇರಿಸಿ", modalRole:"ಪಾತ್ರ", roleUser:"ಬಳಕೆದಾರ", roleAdmin:"ಅಡ್ಮಿನ್", modalDefaultPwd:"ಆರಂಭಿಕ ಪಾಸ್‌ವರ್ಡ್",
  saveBtn:"ಉಳಿಸಿ", cancelBtn:"ರದ್ದುಮಾಡಿ", confirmBtn:"ಅಳಿಸಿ", emptyAnswer:"—"
},
bn: {
  tagline:"আপনার ব্যক্তিগত অগ্রগতি, একটি মানচিত্রে।", signOut:"সাইন আউট",
  navAdmin:"অ্যাডমিন কনসোল", navMySwot:"আমার SWOT",
  authTitle:"স্বাগতম", authSubtitle:"পেশাগতভাবে ভাবা, পরিকল্পনা করা ও এগিয়ে যাওয়ার জন্য আপনার ব্যক্তিগত জায়গা।",
  emailLabel:"ইমেইল ঠিকানা", emailPlaceholder:"you@company.com", continueBtn:"এগিয়ে যান",
  newUserNotice:"আপনি এখানে নতুন — অ্যাকাউন্ট তৈরি করতে পাসওয়ার্ড সেট করুন।",
  returningNotice:"আবার স্বাগতম! সাইন ইন করতে পাসওয়ার্ড দিন।",
  nameLabel:"পুরো নাম", namePlaceholder:"যেমন প্রিয়া শর্মা",
  passwordLabel:"পাসওয়ার্ড", confirmPasswordLabel:"পাসওয়ার্ড নিশ্চিত করুন",
  createAccountBtn:"অ্যাকাউন্ট তৈরি করুন", signInBtn:"সাইন ইন", backBtn:"পিছনে",
  demoHint:"ডেমো অ্যাডমিন: admin@cakewala.in · পাসওয়ার্ড: admin123",
  errEmail:"অনুগ্রহ করে একটি বৈধ ইমেইল ঠিকানা দিন।", errName:"অনুগ্রহ করে আপনার নাম দিন।",
  errPasswordShort:"পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে।", errPasswordMismatch:"পাসওয়ার্ড মিলছে না।",
  errWrongPassword:"ভুল পাসওয়ার্ড। আবার চেষ্টা করুন।",
  toastWelcome:"আবার স্বাগতম, {name}!", toastAccountCreated:"অ্যাকাউন্ট তৈরি হয়েছে। স্বাগতম, {name}!",
  qTitle:"স্মার্ট SWOT প্রশ্নাবলী", qIntro:"নিজের SWOT জানার দরকার নেই — সহজ ও সৎভাবে উত্তর দিন। আপনার উত্তর পড়ে প্রোগ্রামই তা তৈরি করবে।",
  stepWork:"কাজের ধরন", stepStories:"আপনার অভিজ্ঞতা", stepEnv:"আপনার পরিবেশ",
  workIntro:"প্রতিটি বক্তব্য আপনার সঙ্গে কতটা মেলে তা চিহ্নিত করুন। সঠিক-ভুল উত্তর নেই।",
  storiesIntro:"নিজের ভাষায় লিখুন — আপনার বর্ণনা পড়ে প্রোগ্রাম আপনার শক্তি ও দুর্বলতা খুঁজে বের করবে।",
  envIntro:"এবার আপনার ভূমিকার চারপাশের জগৎ নিয়ে কয়েকটি বক্তব্য।",
  scaleLow:"একেবারেই একমত নই", scaleHigh:"সম্পূর্ণ একমত",
  lkHelp:"সহকর্মীরা আমার কাজের ক্ষেত্রে সাহায্য বা পরামর্শের জন্য প্রায়ই আমার কাছে আসেন।",
  lkDeadline:"মনে করিয়ে না দিলেও আমি সময়মতো বা আগেই কাজ শেষ করি।",
  lkPresent:"সিনিয়র বা দলের সামনে নিজের ভাবনা তুলে ধরতে আমি আত্মবিশ্বাসী।",
  lkPostpone:"কঠিন, অস্পষ্ট বা একঘেয়ে কাজ আমি প্রায়ই ফেলে রাখি।",
  lkLearn:"নতুন টুল ও পদ্ধতি আমি সহকর্মীদের চেয়ে দ্রুত শিখি।",
  lkNo:"'না' বলা কঠিন লাগে, তাই প্রায়ই অতিরিক্ত কাজ নিয়ে ফেলি।",
  lkGrowth:"আমার শিল্পখাত বাড়ছে এবং নতুন ধরনের ভূমিকা তৈরি হচ্ছে।",
  lkNetwork:"ক্যারিয়ারে সাহায্য করতে পারেন এমন টিমের বাইরের মানুষদের সঙ্গে নিয়মিত কথা বলি।",
  lkAuto:"আমার দৈনন্দিন কাজের বড় অংশ সফটওয়্যার বা AI করতে পারে।",
  lkPace:"আমার ভূমিকার প্রয়োজনীয় দক্ষতা আমার শেখার গতির চেয়ে দ্রুত বদলাচ্ছে।",
  lkTrain:"আমার প্রতিষ্ঠান প্রশিক্ষণ, মেন্টরিং বা যোগ দেওয়ার মতো প্রকল্প দেয়।",
  tpProud:"সম্প্রতি গর্ব করার মতো একটি কাজের কথা লিখুন। ঠিক কী ভালো করেছিলেন?",
  tpDrain:"কোন কাজ আপনি ফেলে রাখেন বা কোনটি সবচেয়ে ক্লান্তিকর? কেন কঠিন লাগে?",
  tpFeedback:"আপনার সম্পর্কে — প্রশংসা বা সমালোচনা — কোন কথাটি কর্মক্ষেত্রে একাধিকবার শুনেছেন?",
  tpFuture:"আগামী ২–৩ বছরে আপনার ক্ষেত্রে কী কী পরিবর্তন আশা করছেন? (নতুন প্রযুক্তি, প্রতিযোগিতা, চাহিদা…)",
  storyPlaceholder:"কয়েকটি সৎ বাক্য লিখুন…",
  errLikert:"অনুগ্রহ করে এই অংশের সব বক্তব্যের উত্তর দিন।",
  errStories:"অনুগ্রহ করে অন্তত একটি বর্ণনা লিখুন।",
  fromYourWords:"আপনার নিজের ভাষায়:",
  derivedNote:"এই অন্তর্দৃষ্টিগুলো আপনার উত্তর ও বর্ণনা থেকে স্বয়ংক্রিয়ভাবে তৈরি হয়েছে।",
  dvHelpHigh:"বিশেষজ্ঞ পরিচিতি — সহকর্মীরা সক্রিয়ভাবে আপনার পরামর্শ চান।",
  dvHelpLow:"কম দৃশ্যমানতা — আপনার দক্ষতা এখনও সহকর্মীদের কাছে স্বীকৃত নয়।",
  dvDeadlineHigh:"নির্ভরযোগ্য ডেলিভারি — তদারকি ছাড়াই সময়সীমা রক্ষা করেন।",
  dvDeadlineLow:"সময় ব্যবস্থাপনা — বাইরের চাপ ছাড়া সময়সীমা পিছিয়ে যায়।",
  dvPresentHigh:"আত্মবিশ্বাসী যোগাযোগকারী — সিনিয়রদের সামনেও স্বচ্ছন্দ।",
  dvPresentLow:"উপস্থাপনার আত্মবিশ্বাস — সিনিয়রদের সামনে ভাবনা বলা কঠিন লাগে।",
  dvPostponeHigh:"দীর্ঘসূত্রিতা — কঠিন বা অস্পষ্ট কাজ পিছোতে থাকে।",
  dvPostponeLow:"দৃঢ় আত্মনিয়ন্ত্রণ — কঠিন কাজ সরাসরি মোকাবিলা করেন।",
  dvLearnHigh:"দ্রুত শিক্ষার্থী — নতুন টুল সহকর্মীদের চেয়ে দ্রুত আয়ত্ত করেন।",
  dvLearnLow:"শেখার গতি — নতুন টুলে বাড়তি সময় লাগে।",
  dvNoHigh:"অতিরিক্ত দায় — 'না' বলতে না পারায় চাপ বাড়ে।",
  dvNoLow:"সুস্থ সীমারেখা — কাজের চাপ পরিকল্পিতভাবে সামলান।",
  dvGrowthHigh:"ক্রমবর্ধমান শিল্পখাত আপনার চারপাশে নতুন ভূমিকা তৈরি করছে।",
  dvGrowthLow:"স্থবির শিল্পখাত আপনার ক্ষেত্রের সুযোগ সীমিত করতে পারে।",
  dvNetworkHigh:"টিমের বাইরের নেটওয়ার্ক অপ্রত্যাশিত দরজা খুলতে পারে।",
  dvNetworkLow:"টিমের বাইরে সীমিত পেশাদার নেটওয়ার্ক।",
  dvAutoHigh:"অটোমেশনের ঝুঁকি — রুটিন কাজের অংশ স্বয়ংক্রিয় হতে পারে।",
  dvPaceHigh:"দক্ষতা-ঘাটতির ঝুঁকি — চাহিদা আপনার শেখার চেয়ে দ্রুত বদলাচ্ছে।",
  dvPaceLow:"ভূমিকার বদলাতে থাকা চাহিদার সঙ্গে তাল মিলিয়ে চলছেন।",
  dvTrainHigh:"অভ্যন্তরীণ প্রশিক্ষণ, মেন্টরিং ও প্রকল্প আপনার নাগালে।",
  dvTrainLow:"অভ্যন্তরীণ উন্নয়ন-সম্পদ কম — অগ্রগতি নিজের উদ্যোগের উপর নির্ভর।",
  dvDefaultS:"ধারাবাহিক, নির্ভরযোগ্য দৈনন্দিন কর্মদক্ষতা।",
  dvDefaultW:"বড় কোনো দুর্বলতা ধরা পড়েনি — অন্ধ দিক নিয়ে সজাগ থাকুন।",
  dvDefaultO:"সব শিল্পে AI টুলের ব্যবহার বাড়ছে — আগে থেকেই শিখুন।",
  dvDefaultT:"বাজারের সাধারণ পরিবর্তন — দক্ষতা হালনাগাদ রাখুন।",
  stepOf:"ধাপ {n} / {total}",
  stepProfile:"প্রোফাইল", stepStrengths:"শক্তি", stepWeaknesses:"দুর্বলতা", stepOpportunities:"সুযোগ", stepThreats:"ঝুঁকি",
  profileTitle:"আপনার ভূমিকা সম্পর্কে বলুন",
  roleLabel:"পদ / ভূমিকা", rolePlaceholder:"যেমন প্রোডাক্ট ম্যানেজার",
  industryLabel:"শিল্পখাত", industryPlaceholder:"যেমন প্রযুক্তি, অর্থনীতি, স্বাস্থ্যসেবা",
  smartAssistBtn:"স্মার্ট অ্যাসিস্ট", smartAssistHint:"আপনার প্রোফাইলের জন্য ইন্ডাস্ট্রি-মান বেঞ্চমার্ক নিয়ে আসে।",
  smartAssistLoading:"ইন্ডাস্ট্রি বেঞ্চমার্ক বিশ্লেষণ চলছে…", smartAssistTitle:"আপনার প্রোফাইলের জন্য বেঞ্চমার্ক",
  saSkills:"প্রত্যাশিত মূল দক্ষতা", saTrends:"লক্ষ্য রাখার মতো প্রবণতা",
  attachTitle:"ডকুমেন্ট সংযুক্ত করুন (ঐচ্ছিক)", attachHint:"রেজ়্যুমে, SOP বা পারফরম্যান্স রিভিউ — এর প্রসঙ্গ বিশ্লেষণে যুক্ত হবে।",
  attachBtn:"ফাইল বাছুন", attachedMsg:"সংযুক্ত: {file}",
  internalTag:"অভ্যন্তরীণ", externalTag:"বাহ্যিক",
  sIntro:"যা আপনি ইতিমধ্যে ভালো করেন।",
  sQ1:"সহকর্মীরা কোন মূল দক্ষতার জন্য আপনার উপর নির্ভর করেন?", sQ2:"এ বছরের কোন অর্জন নিয়ে আপনি সবচেয়ে গর্বিত?", sQ3:"একই ভূমিকার সহকর্মীদের তুলনায় আপনার বিশেষ সুবিধা কী?",
  wIntro:"যেখানে আপনার বেড়ে ওঠার সুযোগ আছে।",
  wQ1:"কোন দক্ষতার ঘাটতি আপনাকে সবচেয়ে বেশি ধীর করে?", wQ2:"বর্তমানে আপনার কোন সম্পদ বা সহায়তার অভাব রয়েছে?", wQ3:"কোন কাজগুলো আপনি প্রায়ই ফেলে রাখেন?",
  oIntro:"বাহ্যিক সম্ভাবনা যা আপনি কাজে লাগাতে পারেন।",
  oQ1:"আগামী ১–২ বছরে কোন ইন্ডাস্ট্রি প্রবণতার সুবিধা নিতে পারেন?", oQ2:"কোন মানুষ বা নেটওয়ার্ক আপনার জন্য নতুন দরজা খুলতে পারে?", oQ3:"কোন আসন্ন প্রযুক্তি বা দক্ষতা আপনার মূল্য বাড়াবে?",
  tIntro:"যে বাহ্যিক ঝুঁকির জন্য প্রস্তুতি দরকার।",
  tQ1:"আপনার চাকরির বাজারে প্রতিযোগিতা কোথায় সবচেয়ে বেশি?", tQ2:"আপনার ভূমিকার কোন অংশ অটোমেশন বা AI বদলে দিতে পারে?", tQ3:"আপনার ভূমিকার চাহিদা কীভাবে বদলাচ্ছে?",
  moreDetails:"আরও বিস্তারিত যোগ করুন (ঐচ্ছিক)", moreDetailsPlaceholder:"বিশ্লেষণে বিবেচনার জন্য আর কিছু…",
  nextBtn:"পরবর্তী", prevBtn:"পূর্ববর্তী", submitBtn:"আমার বিশ্লেষণ তৈরি করুন",
  errAnswerOne:"এই অংশে অন্তত একটি প্রশ্নের উত্তর দিন।", errProfile:"অনুগ্রহ করে আপনার ভূমিকা ও শিল্পখাত পূরণ করুন।",
  toastSaved:"বিশ্লেষণ সংরক্ষিত হয়েছে। দারুণ!",
  dashTitle:"আপনার ব্যক্তিগত SWOT বিশ্লেষণ",
  strengths:"শক্তি", weaknesses:"দুর্বলতা", opportunities:"সুযোগ", threats:"ঝুঁকি",
  attachedContext:"“{file}”-এর প্রসঙ্গ এই বিশ্লেষণে যুক্ত করা হয়েছে।",
  growthTitle:"গ্রোথ গাইড ও পরবর্তী পদক্ষেপ",
  roadmapTitle:"ক্যারিয়ার রোডম্যাপ ও আপস্কিলিং গাইড",
  roadmapIntro:"আপনার ভূমিকা ও শিল্পখাত অনুযায়ী নির্বাচিত।",
  upskillTitle:"এখন যেসব দক্ষতা গড়বেন",
  coursesTitle:"প্রস্তাবিত কোর্স ও সার্টিফিকেশন",
  nextLevelTitle:"পরের ধাপে যাবেন যেভাবে",
  caseStudyTitle:"বাস্তব কেস স্টাডিজ",
  storyTitle:"বাস্তব অনুপ্রেরণা",
  takeawayLabel:"শিক্ষা",
  successionTitle:"ক্যারিয়ার উত্তরাধিকার পথ",
  successionIntro:"এই ক্ষেত্রের সাধারণ ভূমিকা মই, আপনার পদ অনুযায়ী।",
  youAreHereBadge:"আপনি এখানে আছেন",
  nextMoveLabel:"সাধারণ পরবর্তী পদক্ষেপ",
  focusLabel:"ফোকাস",
  gSO:"কাজে লাগান: শক্তি → সুযোগ", gWO:"উন্নতি করুন: সুযোগ → দুর্বলতা", gST:"রক্ষা করুন: শক্তি বনাম ঝুঁকি", gWT:"কমান: দুর্বলতা × ঝুঁকি",
  tplSO:"আপনার শক্তি “{s}”-কে সুযোগ “{o}”-এর সঙ্গে যুক্ত করুন। এমন কাজে এগিয়ে আসুন যেখানে এই সমন্বয় সিদ্ধান্তগ্রহণকারীদের চোখে পড়ে।",
  tplWO:"“{w}”-এর উপর কাজ করার একটি কাঠামোবদ্ধ উপায় হিসেবে “{o}” ব্যবহার করুন — নতুন কিছুর সঙ্গে যুক্ত হলে উন্নতি টেকসই হয়।",
  tplST:"“{t}”-এর বিরুদ্ধে আপনার শক্তি “{s}” সেরা প্রতিরক্ষা। এটি ধারালো রাখুন এবং দলের বাইরেও পরিচিত করুন।",
  tplWT:"“{w}” ও “{t}” মিলে আপনার সবচেয়ে ঝুঁকিপূর্ণ ক্ষেত্র। ৯০ দিনের উন্নয়ন পরিকল্পনা করুন এবং ঘাটতি পূরণে মেন্টর বা কোর্স খুঁজুন।",
  planTitle:"প্রস্তাবিত ৩০/৬০/৯০ দিনের পরিকল্পনা",
  plan30:"দিন ১–৩০: আপনার শক্তিগুলো লিখে রাখুন এবং একটি দৃশ্যমান সাফল্য ম্যানেজারের সঙ্গে ভাগ করুন।",
  plan60:"দিন ৩১–৬০: আপনার প্রধান দুর্বলতা লক্ষ্য করে একটি কোর্স বা প্রকল্প শুরু করুন।",
  plan90:"দিন ৬১–৯০: একটি সুযোগে পদক্ষেপ নিন — সার্টিফিকেশন, নেটওয়ার্ক বা চ্যালেঞ্জিং অ্যাসাইনমেন্ট।",
  retakeBtn:"প্রশ্নাবলী আবার পূরণ করুন", downloadPdfBtn:"পিডিএফ ডাউনলোড করুন",
  adminTitle:"ইউনিভার্সাল অ্যাডমিন কনসোল", adminSubtitle:"টিম ওভারভিউ, ব্যবহারকারী ব্যবস্থাপনা ও সমন্বিত বিশ্লেষণ।",
  mUsers:"মোট ব্যবহারকারী", mCompleted:"সম্পন্ন বিশ্লেষণ", mRate:"সমাপ্তির হার", mPending:"অপেক্ষমাণ",
  themesTitle:"সাধারণ থিম", themesStrengths:"দলের শীর্ষ শক্তি", themesThreats:"দলের শীর্ষ ঝুঁকি", themesEmpty:"এখনও যথেষ্ট ডেটা নেই।",
  viewBtn:"দেখুন", backToConsole:"কনসোলে ফিরুন",
  vaTitle:"টিম SWOT বিশ্লেষণ", vaSelectUser:"টিম সদস্য", vaNewest:"নতুন আগে", vaOldest:"পুরনো আগে",
  vaCompletedOn:"{date} তারিখে সম্পন্ন", vaNone:"এখনও কোনো সম্পন্ন বিশ্লেষণ নেই।",
  usersTitle:"ব্যবহারকারী ব্যবস্থাপনা",
  colName:"নাম", colEmail:"ইমেইল", colCreated:"তৈরি", colStatus:"অবস্থা", colActions:"কার্যক্রম",
  statusDone:"সম্পন্ন", statusPending:"অপেক্ষমাণ",
  addUserBtn:"নতুন ব্যবহারকারী যোগ করুন", resetPwdBtn:"পাসওয়ার্ড রিসেট", deleteBtn:"মুছুন", adminBadge:"অ্যাডমিন",
  confirmDeleteTitle:"ব্যবহারকারী মুছবেন?", confirmDelete:"{name} এবং তাঁর বিশ্লেষণ মুছবেন? এটি ফেরানো যাবে না।",
  toastUserAdded:"ব্যবহারকারী {name} যোগ হয়েছে।", toastUserDeleted:"ব্যবহারকারী মুছে ফেলা হয়েছে।", toastPwdReset:"পাসওয়ার্ড “{pwd}”-এ রিসেট হয়েছে।",
  errUserExists:"এই ইমেইলে ইতিমধ্যে একজন ব্যবহারকারী আছেন।",
  modalAddTitle:"নতুন ব্যবহারকারী যোগ করুন", modalRole:"ভূমিকা", roleUser:"ব্যবহারকারী", roleAdmin:"অ্যাডমিন", modalDefaultPwd:"প্রাথমিক পাসওয়ার্ড",
  saveBtn:"সংরক্ষণ", cancelBtn:"বাতিল", confirmBtn:"মুছুন", emptyAnswer:"—"
}
};
export const LOCALES = { en:"en-IN", hi:"hi-IN", kn:"kn-IN", bn:"bn-IN" };

export const QUADS = {
  s: { icon:"zap",          color:"emerald", tag:"internalTag", titleKey:"stepStrengths",     introKey:"sIntro", qs:["sQ1","sQ2","sQ3"] },
  w: { icon:"wrench",       color:"amber",   tag:"internalTag", titleKey:"stepWeaknesses",    introKey:"wIntro", qs:["wQ1","wQ2","wQ3"] },
  o: { icon:"trending-up",  color:"indigo",  tag:"externalTag", titleKey:"stepOpportunities", introKey:"oIntro", qs:["oQ1","oQ2","oQ3"] },
  t: { icon:"shield-alert", color:"rose",    tag:"externalTag", titleKey:"stepThreats",       introKey:"tIntro", qs:["tQ1","tQ2","tQ3"] }
};
export const STEPS = ["profile", "work", "stories", "env"];

/* Indirect self-assessment items. The user never labels their own SWOT —
   each statement's score is mapped by the engine into the right quadrant.
   high = agree (4-5), low = disagree (1-2); each side maps to a quadrant + insight key. */
export const LIKERT = [
  { id:"lkHelp",     step:"work", high:{q:"s",k:"dvHelpHigh"},     low:{q:"w",k:"dvHelpLow"} },
  { id:"lkDeadline", step:"work", high:{q:"s",k:"dvDeadlineHigh"}, low:{q:"w",k:"dvDeadlineLow"} },
  { id:"lkPresent",  step:"work", high:{q:"s",k:"dvPresentHigh"},  low:{q:"w",k:"dvPresentLow"} },
  { id:"lkPostpone", step:"work", high:{q:"w",k:"dvPostponeHigh"}, low:{q:"s",k:"dvPostponeLow"} },
  { id:"lkLearn",    step:"work", high:{q:"s",k:"dvLearnHigh"},    low:{q:"w",k:"dvLearnLow"} },
  { id:"lkNo",       step:"work", high:{q:"w",k:"dvNoHigh"},       low:{q:"s",k:"dvNoLow"} },
  { id:"lkGrowth",   step:"env",  high:{q:"o",k:"dvGrowthHigh"},   low:{q:"t",k:"dvGrowthLow"} },
  { id:"lkNetwork",  step:"env",  high:{q:"o",k:"dvNetworkHigh"},  low:{q:"w",k:"dvNetworkLow"} },
  { id:"lkAuto",     step:"env",  high:{q:"t",k:"dvAutoHigh"},     low:null },
  { id:"lkPace",     step:"env",  high:{q:"t",k:"dvPaceHigh"},     low:{q:"s",k:"dvPaceLow"} },
  { id:"lkTrain",    step:"env",  high:{q:"o",k:"dvTrainHigh"},    low:{q:"t",k:"dvTrainLow"} }
];

/* Free-text prompts whose descriptions are mined for SWOT evidence. */
export const TEXTS = [
  { id:"proud",    step:"stories", promptKey:"tpProud" },
  { id:"drain",    step:"stories", promptKey:"tpDrain" },
  { id:"feedback", step:"stories", promptKey:"tpFeedback" },
  { id:"future",   step:"env",     promptKey:"tpFuture" }
];

export const BENCHMARKS = [
  { match:/tech|software|it\b|engineer|developer|\bproduct\b|data|design|ux/i,
    skills:["System thinking & problem decomposition","Cloud & AI-assisted tooling fluency","Cross-functional communication","Data-informed decision making"],
    trends:["GenAI copilots reshaping day-to-day workflows","Platform consolidation & DevEx focus","Privacy-first product design"],
    grow:[
      { skill:"Cloud & AI tooling (AWS/Azure + GenAI copilots)", why:"Every modern tech role now touches cloud infrastructure and AI-assisted workflows — fluency here is the new baseline." },
      { skill:"System design & architecture", why:"This is what separates senior engineers from mid-level ones in both promotions and interviews." },
      { skill:"Communication & documentation", why:"Your work only counts when decision-makers understand it — write and present as deliberately as you build." }
    ],
    courses:[
      { name:"Google IT / Data / Project Management certificates", by:"Coursera" },
      { name:"AWS Cloud Practitioner + Skill Builder paths", by:"Amazon, many free" },
      { name:"Machine Learning Specialization (Andrew Ng)", by:"DeepLearning.AI / Coursera" },
      { name:"Full-stack curriculum", by:"freeCodeCamp, free" }
    ],
    levelUp:[
      "Own one service or feature end-to-end, and document its measurable wins.",
      "Mentor one junior — teaching is the fastest visibility multiplier there is.",
      "Give one tech talk or write one internal blog post every quarter.",
      "Ask your manager, in writing, what 'the next level' means here — then close that list item by item."
    ],
    caseStudies:[
      { title:"Microsoft's reskilling pivot",
        body:"When Satya Nadella became CEO in 2014, Microsoft was widely seen as a fading giant. He bet the company on cloud and demanded a 'learn-it-all' culture over a 'know-it-all' one — thousands of Windows-era engineers retrained on Azure and AI. A decade later Microsoft crossed a $3-trillion valuation, powered largely by people who upskilled rather than being replaced.",
        takeaway:"The skill you learn before it becomes urgent is the one that pays the most." },
      { title:"Infosys Mysore: the campus that manufactures careers",
        body:"Infosys built the world's largest corporate training centre — a 337-acre campus in Mysore — to take fresh engineering graduates with little practical skill and turn them into billable global consultants through a rigorous months-long foundation program. It runs on an explicit, well-known internal ladder (Systems Engineer → Technology Analyst → Technology Lead → Project Manager) that the whole Indian IT industry now benchmarks against.",
        takeaway:"A well-designed internal ladder turns raw graduates into a company's biggest competitive asset." }
    ],
    story:{
      title:"From a home with no telephone to Google CEO",
      body:"Sundar Pichai grew up in Chennai in a two-room flat; his family got its first telephone when he was twelve. A scholarship took him to Stanford, and at Google he kept deliberately learning adjacent skills — materials engineering to product to leadership. He championed Chrome when many inside Google doubted a browser mattered, and that bet carried him to CEO of Google and Alphabet.",
      quote:"Wear your failure as a badge of honour." },
    ladder:[
      { title:"Graduate / Trainee Engineer", years:"0–1 yrs", focus:"Learning the codebase, tools and delivery process under close mentorship.", re:/intern|trainee|fresher|graduate engineer/i },
      { title:"Software Engineer / Analyst", years:"1–3 yrs", focus:"Owns individual features or modules with moderate supervision; builds technical depth." },
      { title:"Senior Engineer / Consultant", years:"3–6 yrs", focus:"Owns systems end-to-end, mentors juniors, makes design decisions within a team.", re:/senior|sr\.?\s|consultant/i },
      { title:"Tech Lead / Engineering Manager", years:"6–10 yrs", focus:"Sets technical direction for a team or leads people — the IC-vs-management fork.", re:/lead|principal|staff|engineering manager|\bem\b|architect/i },
      { title:"Director / VP Engineering / CTO", years:"10+ yrs", focus:"Owns technology strategy across multiple teams, tied to business outcomes.", re:/\bcto\b|chief technology|vice president|\bvp\b|director/i }
    ] },

  { match:/financ|bank|invest(?!igat)|account|audit|insur/i,
    skills:["Regulatory awareness (RBI/SEBI/Basel)","Financial modelling & scenario analysis","Stakeholder reporting","Fintech platform literacy"],
    trends:["Embedded finance & UPI-scale rails","AI-driven risk scoring","ESG-linked reporting requirements"],
    grow:[
      { skill:"Data-driven analysis (Excel → Python / Power BI)", why:"Manual reporting is being automated; analysis and judgment are not — move up the value chain." },
      { skill:"Regulatory & risk fluency", why:"Compliance depth is a moat that automation cannot cross quickly." },
      { skill:"Client advisory & storytelling with numbers", why:"Advice, not data entry, is where finance careers are heading." }
    ],
    courses:[
      { name:"CFA Program (start with Level 1)", by:"CFA Institute" },
      { name:"Financial Markets — Robert Shiller (Yale)", by:"Coursera, free to audit" },
      { name:"FMVA — Financial Modeling & Valuation Analyst", by:"CFI" },
      { name:"NISM certifications for Indian market roles", by:"NISM" }
    ],
    levelUp:[
      "Automate one recurring report — then present the hours saved to your manager.",
      "Volunteer for the notes and follow-ups in client or leadership meetings; it puts you in the room.",
      "Pick one credential (CFA L1, FMVA, NISM) and finish it within twelve months.",
      "Build a reputation for one niche — 'ask them about X' is how promotions start."
    ],
    caseStudies:[
      { title:"DBS: the bank that retrained itself",
        body:"In the mid-2010s Singapore's DBS decided to act 'less like a bank, more like a tech company'. Instead of hiring its way out, it retrained tens of thousands of existing employees in digital tools, data and agile working. DBS went on to be named the world's best bank multiple times by Euromoney and Global Finance — with largely the same people, carrying new skills.",
        takeaway:"Institutions bet on people who retrain — and so do promotion committees." },
      { title:"ICICI's 'CEO factory'",
        body:"Under K.V. Kamath, ICICI Bank became famous for aggressively rotating promising employees across functions — retail, corporate banking, technology — and grooming them for leadership far earlier than peers. The results are documented: alumni went on to become CEOs of Kotak Mahindra, Axis Bank, IndusInd Bank and more, an unusually concentrated leadership export for one institution.",
        takeaway:"Deliberate cross-functional rotation, not tenure alone, is what production-lines great leaders." }
    ],
    story:{
      title:"Buffett's $100 course",
      body:"As a young man, Warren Buffett was so terrified of public speaking that he would feel physically sick before presentations. He enrolled in a $100 Dale Carnegie course and, to force himself to practise, immediately took a job teaching an investment class. He still says that certificate — not his degrees — hangs in his office, because learning to communicate multiplied the value of everything else he knew.",
      quote:"Investing in yourself is the best investment you will ever make." },
    ladder:[
      { title:"Management Trainee / Junior Analyst", years:"0–2 yrs", focus:"Learning products, systems and compliance basics under supervision.", re:/trainee|intern|junior/i },
      { title:"Analyst / Officer / Executive", years:"1–3 yrs", focus:"Handles a book of accounts, transactions or analysis with growing independence." },
      { title:"Senior Analyst / Deputy Manager", years:"3–6 yrs", focus:"Owns a portfolio or process, reviews juniors' work, client-facing.", re:/senior|deputy manager|associate/i },
      { title:"Manager / AVP", years:"6–10 yrs", focus:"Owns a team's numbers and risk, represents the function to other departments.", re:/manager|\bavp\b|assistant vice president/i },
      { title:"VP / Director / CFO", years:"10+ yrs", focus:"Sets strategy for a business line or the whole finance function.", re:/\bvp\b|vice president|director|\bcfo\b|general manager/i }
    ] },

  { match:/health|medical|pharma|clinic|hospital(?!ity)|nurse(?!ry)|doctor/i,
    skills:["Patient-centred communication","Clinical documentation quality","Digital health record systems","Interdisciplinary coordination"],
    trends:["Telemedicine as a default channel","AI-assisted diagnostics","Value-based care metrics"],
    grow:[
      { skill:"Digital health systems (EMR / telemedicine platforms)", why:"Care delivery is shifting to hybrid digital channels — comfort with these systems is now expected." },
      { skill:"Data literacy & quality metrics", why:"Value-based care rewards professionals who can measure and improve outcomes." },
      { skill:"Patient communication & empathy at scale", why:"The one skill machines cannot replicate — and the most cited factor in both praise and complaints." }
    ],
    courses:[
      { name:"Healthcare courses from Johns Hopkins & Yale", by:"Coursera" },
      { name:"Clinical update modules", by:"BMJ Learning" },
      { name:"PG diploma in hospital & healthcare management", by:"IGNOU / Symbiosis" },
      { name:"Health data analytics basics", by:"edX / NPTEL, free" }
    ],
    levelUp:[
      "Join one quality-improvement or accreditation project (NABH/JCI) — it teaches you the system, not just your station.",
      "Learn your institution's numbers — bed turnover, infection rates, waiting times — and speak that language with management.",
      "Take one management or leadership module; clinical skill alone eventually caps out.",
      "Find a senior mentor outside your own department for perspective."
    ],
    caseStudies:[
      { title:"Aravind: assembly-line compassion",
        body:"Dr. G. Venkataswamy founded Aravind Eye Care in Madurai at age 58 with 11 beds. By adapting McDonald's-style standardised workflows and training rural young women into highly skilled ophthalmic technicians, Aravind became the world's largest eye-care network — hundreds of thousands of surgeries a year, most free or subsidised, yet financially self-sustaining. It is now a Harvard Business School case study.",
        takeaway:"Upskilling ordinary people inside extraordinary systems beats waiting for extraordinary people." },
      { title:"Cleveland Clinic's 'caregiver' model",
        body:"Cleveland Clinic salaries every physician instead of paying per procedure, and built its whole promotion and culture system around quality metrics and teamwork rather than individual volume. The realignment of incentives — not new technology — is what business schools cite for its consistent top ranking among US hospital systems.",
        takeaway:"How a system pays and promotes people shapes outcomes more than the technology it buys." }
    ],
    story:{
      title:"The surgeon who scaled kindness",
      body:"Dr. Devi Shetty, once Mother Teresa's cardiac surgeon, kept asking one question: why should heart surgery cost so much? He built Narayana Health from a single Bengaluru hospital into one of the world's highest-volume cardiac centres, using skill-volume and process discipline to push costs down — proving world-class care and affordability can coexist.",
      quote:"If a solution is not affordable, it is not a solution." },
    ladder:[
      { title:"Intern / House Surgeon / Staff Nurse Trainee", years:"0–1 yrs", focus:"Supervised clinical rotations, building hands-on fundamentals.", re:/intern|house surgeon|trainee/i },
      { title:"Resident / Medical Officer / Staff Nurse", years:"1–4 yrs", focus:"Manages patients directly under a consultant's supervision." },
      { title:"Senior Resident / Registrar / Charge Nurse", years:"4–7 yrs", focus:"Leads a ward or shift, supervises juniors, handles complex cases.", re:/senior resident|registrar|charge nurse/i },
      { title:"Consultant / Department Head", years:"7–12 yrs", focus:"Owns clinical outcomes for a department, trains residents.", re:/consultant|department head|nursing superintendent/i },
      { title:"Senior Consultant / Medical Director / CMO", years:"12+ yrs", focus:"Sets clinical policy and standards across the institution.", re:/medical director|chief medical officer|\bcmo\b|director of nursing/i }
    ] },

  { match:/market|sales|brand|growth|content|seo|advertis/i,
    skills:["Full-funnel analytics","Storytelling & positioning","Marketing automation platforms","Community-led growth tactics"],
    trends:["AI-generated content at scale (and its trust gap)","First-party data strategies","Short-form video dominance"],
    grow:[
      { skill:"Full-funnel analytics (GA4, attribution, CRM data)", why:"Budgets follow the people who can prove what worked." },
      { skill:"AI-assisted content & automation tools", why:"Output per marketer is being redefined — drive the tools rather than compete with them." },
      { skill:"Consultative selling & storytelling", why:"Trust and narrative close deals that discounts cannot." }
    ],
    courses:[
      { name:"Google Digital Marketing & E-commerce certificate", by:"Coursera" },
      { name:"Inbound, content & sales certifications", by:"HubSpot Academy, free" },
      { name:"Meta Blueprint certifications", by:"Meta" },
      { name:"Consultative selling learning paths", by:"LinkedIn Learning" }
    ],
    levelUp:[
      "Own one number — leads, conversion or retention — and report on it monthly, unasked.",
      "Build a mini-portfolio: three campaigns or deals with before/after data.",
      "Shadow the best closer or marketer in your organisation for a quarter.",
      "Present one experiment per quarter to leadership — visibility compounds like interest."
    ],
    caseStudies:[
      { title:"Old Spice: insight beats budget",
        body:"In 2010, Old Spice was a fading 70-year-old brand losing ground to newer rivals. One research insight — women make most household purchases of men's body wash — reshaped the entire campaign. 'The Man Your Man Could Smell Like' spoke to both audiences with humour, sales roughly doubled within months, and a legacy brand became young again overnight.",
        takeaway:"Studying the real buyer harder than the product beats outspending competitors." },
      { title:"HUL's brand-management 'CEO factory'",
        body:"Hindustan Unilever's decades-old brand-management program takes Assistant Brand Managers through a deliberately structured ladder toward general management. It is so effective at producing broad business leaders that HUL alumni now run companies across unrelated Indian industries — one of the most cited talent pipelines in Indian corporate history.",
        takeaway:"A rigorous, well-known internal ladder is itself a powerful employer brand." }
    ],
    story:{
      title:"The fax-machine saleswoman",
      body:"Sara Blakely sold fax machines door-to-door for seven years, collecting rejections daily. At 27, with $5,000 in savings and no fashion background, she cut the feet off her pantyhose, cold-called textile mills until one said yes, and pitched Neiman Marcus with a demo in a bathroom stall. Spanx made her the youngest self-made female billionaire — built on sales resilience learned in the field.",
      quote:"Embrace what you don't know — it can be your biggest asset." },
    ladder:[
      { title:"Marketing Trainee / Intern", years:"0–1 yrs", focus:"Supporting campaigns, learning brand and channel basics.", re:/trainee|intern/i },
      { title:"Marketing Executive / Asst. Brand Manager", years:"1–3 yrs", focus:"Runs individual campaigns or channels with defined targets." },
      { title:"Brand / Marketing Manager", years:"3–6 yrs", focus:"Owns a brand or channel's P&L and strategy end-to-end.", re:/brand manager|marketing manager|senior executive/i },
      { title:"Senior Brand Manager / Marketing Head", years:"6–10 yrs", focus:"Leads a portfolio of brands or the whole marketing function for a unit.", re:/senior brand manager|group product manager|marketing head/i },
      { title:"Marketing Director / VP / CMO", years:"10+ yrs", focus:"Sets brand and growth strategy at the company level.", re:/marketing director|\bvp marketing\b|\bcmo\b/i }
    ] },

  { match:/teach|educat|train|academ|school|professor|l&d/i,
    skills:["Learning experience design","Assessment & feedback systems","Digital classroom tooling","Inclusive pedagogy"],
    trends:["AI tutors & adaptive learning","Micro-credentials over degrees","Hybrid classroom models"],
    grow:[
      { skill:"Digital pedagogy & LMS tools", why:"Hybrid classrooms are now the default expectation, not an add-on." },
      { skill:"Assessment design & learning analytics", why:"Data on learning outcomes is the new appraisal currency." },
      { skill:"Content creation (video, interactive lessons)", why:"Your teaching can scale far beyond one classroom." }
    ],
    courses:[
      { name:"Learning How to Learn", by:"Coursera, free" },
      { name:"Google for Education certifications", by:"Google" },
      { name:"NPTEL / SWAYAM university courses", by:"Govt. of India, free" },
      { name:"Instructional design fundamentals", by:"edX" }
    ],
    levelUp:[
      "Record and publish one lesson online — start building a public teaching footprint.",
      "Lead one teacher-training or curriculum project in your institution.",
      "Collect and present learning-outcome data for your own classes.",
      "Join subject associations and ed-tech communities — opportunities travel through them."
    ],
    caseStudies:[
      { title:"Physics Wallah: from YouTube to unicorn",
        body:"Alakh Pandey taught physics in Allahabad coaching centres, then started a YouTube channel — Physics Wallah — teaching in simple, warm Hindi at near-zero cost to students. Clarity and affordability drew millions of learners, and by 2022 the company became an ed-tech unicorn while charging a fraction of competitors' fees.",
        takeaway:"Mastering delivery and accessibility can out-compete institutions with a hundred times the budget." },
      { title:"Finland's teacher-status model",
        body:"Finland requires every teacher to hold a research-based master's degree and grants them significant classroom autonomy, treating teaching as a prestige profession on par with medicine or law. The result is consistently one of the world's top-performing school systems, built entirely by investing in the career quality of teachers rather than exam pressure on students.",
        takeaway:"Raising the ceiling on a career itself is often the highest-leverage reform available." }
    ],
    story:{
      title:"The tutor who taught the world",
      body:"In 2004, hedge-fund analyst Salman Khan began tutoring his cousin Nadia over the phone, then posted practice videos on YouTube. Strangers kept watching. He eventually left finance to build Khan Academy — a free platform now used by over 100 million learners a year — which started with one student and a $20 microphone.",
      quote:"You can learn anything." },
    ladder:[
      { title:"Teaching Assistant / Trainee Teacher", years:"0–1 yrs", focus:"Assisting lessons and classroom management under supervision.", re:/trainee|teaching assistant|intern/i },
      { title:"Teacher / Subject Teacher", years:"1–4 yrs", focus:"Owns lesson planning and delivery for a subject or class." },
      { title:"Senior Teacher / HoD / Coordinator", years:"4–8 yrs", focus:"Leads a subject department, mentors newer teachers.", re:/senior teacher|head of department|\bhod\b|coordinator/i },
      { title:"Vice Principal / Academic Coordinator", years:"8–14 yrs", focus:"Owns academic outcomes and staff management across the school.", re:/vice principal|academic coordinator|assistant professor/i },
      { title:"Principal / Director / Dean", years:"14+ yrs", focus:"Sets institutional strategy and represents it externally.", re:/principal|\bdirector\b|\bdean\b|professor/i }
    ] },

  { match:/manufactur|production|\bplant\b|factory|industrial|supply chain|logistics/i,
    skills:["Lean / Six Sigma process discipline","Quality & safety systems (ISO/Six Sigma)","Inventory & supply-chain optimisation","Cross-functional shop-floor leadership"],
    trends:["Industry 4.0 & smart-factory sensors","Automation and robotics on the shop floor","Sustainability-driven manufacturing standards"],
    grow:[
      { skill:"Lean Six Sigma (Green/Black Belt)", why:"The shared language of every improvement project and promotion panel in operations." },
      { skill:"Digital shop-floor tools (ERP/MES systems)", why:"Paper-based tracking is disappearing — fluency with the digital layer is now baseline." },
      { skill:"People leadership on the shop floor", why:"Beyond the first few years, your output depends on the team you run, not just your own hands." }
    ],
    courses:[
      { name:"Six Sigma Green/Black Belt", by:"ASQ / Coursera" },
      { name:"Toyota Production System & Lean fundamentals", by:"Coursera / edX" },
      { name:"SAP / ERP basics for operations", by:"SAP Learning" },
      { name:"NPTEL industrial & production engineering courses", by:"Govt. of India, free" }
    ],
    levelUp:[
      "Lead one kaizen / continuous-improvement project and measure the savings in writing.",
      "Get cross-trained on an adjacent line or process.",
      "Complete one safety or quality certification this year.",
      "Volunteer for one cross-plant or vendor-facing project."
    ],
    caseStudies:[
      { title:"Toyota: 1% better, forever",
        body:"Toyota's rise from a small loom-maker's side business to the world's most valuable automaker was powered by kaizen — every worker, at every level, empowered and expected to suggest small improvements daily. Millions of tiny upgrades, compounding for decades, produced world-beating quality no rival could copy quickly.",
        takeaway:"Small, consistent self-improvement compounds into an advantage nobody can take from you." },
      { title:"Maruti Suzuki: building a workforce from scratch",
        body:"When Maruti Suzuki began manufacturing in India in the 1980s, it transferred Japanese process discipline and Total Productive Maintenance directly onto Indian shop floors, training tens of thousands of local technicians and engineers. That knowledge transfer effectively built India's modern auto-manufacturing workforce from the ground up.",
        takeaway:"Rigorous process discipline, transferred deliberately, can build a world-class workforce in a generation." }
    ],
    story:{
      title:"From the assembly line to the CEO's chair",
      body:"Mary Barra started at General Motors at 18 as a co-op student inspecting fender panels on the assembly line, paying her way through engineering school. Over more than three decades she moved through plant management and engineering leadership roles before becoming GM's CEO — the first woman to lead a major global automaker.",
      quote:"You need to know your business, but the best leaders also know their people." },
    ladder:[
      { title:"Trainee / Apprentice / ITI Trainee", years:"0–1 yrs", focus:"Learning machines, safety protocols and standard operating procedures.", re:/apprentice|trainee|\biti\b/i },
      { title:"Shop-floor Engineer / Technician", years:"1–4 yrs", focus:"Runs a process or line with growing independence." },
      { title:"Senior Engineer / Shift In-charge", years:"4–8 yrs", focus:"Owns a shift or section's output and quality.", re:/shift in-?charge|section head|senior engineer/i },
      { title:"Plant / Production Manager", years:"8–14 yrs", focus:"Owns an entire plant's output, cost and people.", re:/plant manager|production manager|operations manager/i },
      { title:"Plant Head / VP Operations / COO", years:"14+ yrs", focus:"Sets operations strategy across plants or the whole company.", re:/plant head|vp operations|\bcoo\b/i }
    ] },

  { match:/\bhr\b|human resources|talent acquisition|recruit|people operations/i,
    skills:["Talent acquisition & employer branding","HR analytics & workforce planning","Employee relations & labour law","Learning & development design"],
    trends:["AI in recruiting and screening","Hybrid-work policy design","Skills-based hiring over degrees"],
    grow:[
      { skill:"HR analytics (Excel / Power BI / HRIS)", why:"Data-backed HR proposals get funded; opinions alone don't." },
      { skill:"Employment law & compliance depth", why:"It's the part of HR that can't be outsourced to a tool, and it protects the whole company." },
      { skill:"Coaching & difficult-conversations skill", why:"The highest-value, least automatable part of the job." }
    ],
    courses:[
      { name:"HR Analytics", by:"Coursera / HRCI" },
      { name:"SHRM-CP / SHRM-SCP certification", by:"SHRM" },
      { name:"National Institute of Personnel Management certifications", by:"NIPM, India" },
      { name:"HR learning paths", by:"LinkedIn Learning" }
    ],
    levelUp:[
      "Build one dashboard tracking attrition or engagement and share it monthly.",
      "Lead one policy or process redesign end-to-end.",
      "Get one HR certification (SHRM/HRCI) within 18 months.",
      "Partner closely with one business unit as their go-to HR person."
    ],
    caseStudies:[
      { title:"Netflix's 'Freedom & Responsibility' deck",
        body:"Netflix's internal culture presentation — built by its HR team — argued for radical honesty, minimal policy and hiring only high performers. Sheryl Sandberg called it possibly the most important document to ever come out of Silicon Valley; it reshaped how a generation of tech companies think about talent density and policy design.",
        takeaway:"HR can produce the single most influential document in a company, not just its policies." },
      { title:"Google's Project Oxygen",
        body:"Google's People Analytics team used internal performance data to identify, empirically, what actually makes managers effective — findings that directly reshaped how the company trains and promotes managers. It turned HR from an administrative function into a data-driven strategic one.",
        takeaway:"Treating people decisions with the same rigour as product decisions changes what HR can achieve." }
    ],
    story:{
      title:"The HR leader who wrote the rules",
      body:"Laszlo Bock joined Google's People Operations team and built it into one of the most admired HR functions in the world, using data to challenge conventional wisdom about hiring, pay and management. He later distilled those lessons into 'Work Rules!' — proof that HR itself can be a serious strategic career, not just an administrative one.",
      quote:"Take a chance on the unconventional hire — potential matters more than pedigree." },
    ladder:[
      { title:"HR Trainee / Intern", years:"0–1 yrs", focus:"Learning recruitment, onboarding and HRIS basics.", re:/trainee|intern/i },
      { title:"HR Executive / Generalist", years:"1–3 yrs", focus:"Handles recruitment, onboarding or employee queries for a unit." },
      { title:"Senior HR Executive / HRBP", years:"3–6 yrs", focus:"Partners with a business unit on people strategy.", re:/senior hr|hr business partner|\bhrbp\b/i },
      { title:"HR Manager / Talent Lead", years:"6–10 yrs", focus:"Owns HR strategy and a team for a function or region.", re:/hr manager|talent lead|senior hrbp/i },
      { title:"HR Director / VP HR / CHRO", years:"10+ yrs", focus:"Sets people strategy at the company level.", re:/hr director|\bvp hr\b|\bchro\b/i }
    ] },

  { match:/legal|lawyer|advocate|counsel|compliance|paralegal/i,
    skills:["Contract drafting & negotiation","Regulatory research & compliance frameworks","Risk assessment & advisory","Cross-border / data-privacy law literacy"],
    trends:["AI-assisted contract review & legal research","Data-privacy law expansion (DPDP Act/GDPR)","Rise of in-house counsel over external firms"],
    grow:[
      { skill:"Legal-tech tools (contract AI, e-discovery)", why:"Routine review is being automated — your value shifts to judgment and negotiation." },
      { skill:"One specialisation (data privacy, IP, M&A)", why:"Generalist legal advice is commoditised; deep specialists command premium roles." },
      { skill:"Business fluency", why:"Legal advice only lands when it's framed in terms the business actually cares about." }
    ],
    courses:[
      { name:"Data Privacy certification (DPDP Act / GDPR)", by:"Coursera / IAPP" },
      { name:"Executive certifications", by:"NALSAR / National Law Universities" },
      { name:"Company Secretary (CS) / LLM specialisations", by:"ICSI / universities" },
      { name:"Legal-tech courses", by:"Coursera / edX" }
    ],
    levelUp:[
      "Take ownership of one contract category end-to-end.",
      "Build a template or playbook that saves the team measurable time.",
      "Get one specialisation certification (privacy, IP, competition law).",
      "Present legal risk in plain business language to leadership once a quarter."
    ],
    caseStudies:[
      { title:"GE's legal department as a strategic function",
        body:"Under General Counsel Ben Heineman, General Electric rebuilt its legal department from a cost centre into a widely-cited strategic function with a strong internal-promotion ladder — producing General Counsels for other Fortune 500 companies for years afterward.",
        takeaway:"A legal department can be run as a leadership pipeline, not just a risk-control function." },
      { title:"GDPR created a C-suite role overnight",
        body:"When the EU's GDPR took effect in 2018, it created sudden, massive demand for a role that barely existed before: the Chief Privacy Officer. Lawyers who had specialised early in data-privacy law — ahead of the regulation — rode a wave of new, well-paid senior roles almost overnight.",
        takeaway:"Specialising ahead of a regulation, not after it, is where the biggest career jumps happen." }
    ],
    story:{
      title:"Building one of India's top law firms from scratch",
      body:"Zia Mody left a well-established New York legal career to return to India and co-found AZB & Partners, growing it into one of the country's most prominent corporate law firms through sheer depth of expertise and relentless client focus, at a time when few large Indian corporate law firms existed at all.",
      quote:"Hard work and mastery of your subject will always be noticed." },
    ladder:[
      { title:"Legal Intern / Trainee Associate", years:"0–1 yrs", focus:"Research and drafting support under a senior lawyer.", re:/intern|trainee/i },
      { title:"Associate / Legal Executive", years:"1–3 yrs", focus:"Drafts and reviews contracts independently on defined matters." },
      { title:"Senior Associate / Asst. Manager - Legal", years:"3–6 yrs", focus:"Owns a portfolio of matters, negotiates directly with counterparties.", re:/senior associate|assistant manager.*legal/i },
      { title:"Manager - Legal / Associate GC", years:"6–10 yrs", focus:"Advises leadership directly, manages a small legal team.", re:/manager.*legal|associate general counsel/i },
      { title:"General Counsel / Head of Legal / VP Legal", years:"10+ yrs", focus:"Owns legal strategy and risk for the whole company.", re:/general counsel|head of legal|vp legal/i }
    ] },

  { match:/retail|e-?commerce|merchandis|d2c\b/i,
    skills:["Inventory & demand planning","Customer experience & omnichannel design","Category / pricing management","Supply-chain & fulfilment operations"],
    trends:["Quick commerce & hyperlocal delivery","AI-driven personalisation & recommendations","D2C brand growth"],
    grow:[
      { skill:"Data-driven merchandising (sales/inventory analytics)", why:"Gut-feel buying is being replaced by data-backed category decisions." },
      { skill:"Omnichannel & digital-commerce platforms", why:"Store and online are converging into one job, not two." },
      { skill:"Customer-experience design", why:"Retention now drives more value than one-time acquisition." }
    ],
    courses:[
      { name:"Google Digital Marketing & E-commerce certificate", by:"Coursera" },
      { name:"Retail management programs", by:"NIFT / IIM Executive Education" },
      { name:"Supply-chain analytics courses", by:"Coursera" },
      { name:"E-commerce platform certifications", by:"Shopify Learn" }
    ],
    levelUp:[
      "Own one category's numbers (sales, margin, stock-outs) and report on it unasked.",
      "Run one pricing or promotion experiment with a measurable result.",
      "Learn the tech stack (POS/ERP/WMS) beyond your own function.",
      "Shadow store-ops or supply-chain teams to see the full flow."
    ],
    caseStudies:[
      { title:"Flipkart's Big Billion Days",
        body:"Flipkart grew from a scrappy Bengaluru startup into a company Walmart valued in the billions, building India's e-commerce playbook — including its own logistics network — largely from scratch, and training tens of thousands of employees along the way.",
        takeaway:"Building the operational backbone yourself, not just the storefront, is what scale actually requires." },
      { title:"Amazon's 'Day 1' culture",
        body:"Amazon's Leadership Principles — a working backwards, customer-obsessed set of behaviours — are used explicitly in every hiring and promotion decision at the company, not just as posters on a wall. That direct link between stated values and career advancement is widely studied as a driver of Amazon's execution speed.",
        takeaway:"When promotion criteria are explicit and consistently applied, people know exactly how to grow." }
    ],
    story:{
      title:"From consulting to Flipkart's CEO",
      body:"Kalyan Krishnamurthy moved from Tiger Global into Flipkart during one of its most turbulent periods, took on operational roles most executives would avoid, and rebuilt the company's core commerce business before becoming its CEO — a reminder that taking the hardest, least glamorous roles is often the fastest path up.",
      quote:"Execution, not strategy alone, is what separates companies that win." },
    ladder:[
      { title:"Management Trainee / Store Associate", years:"0–1 yrs", focus:"Learning store operations, systems and customer service basics.", re:/trainee|associate|intern/i },
      { title:"Category Executive / Store Manager", years:"1–3 yrs", focus:"Owns a category, store, or operations process." },
      { title:"Senior Category Manager / Area Manager", years:"3–6 yrs", focus:"Owns a portfolio of categories or stores across a region.", re:/senior category|area manager/i },
      { title:"Category Head / Regional Manager", years:"6–10 yrs", focus:"Sets category or regional strategy and owns its P&L.", re:/category head|regional manager|ops manager/i },
      { title:"Business Head / VP Retail / CCO", years:"10+ yrs", focus:"Owns commercial strategy across the business.", re:/business head|vp retail|chief commercial officer/i }
    ] },

  { match:/hospitality|hotel|travel|tourism|aviation|airline|restaurant|f&b|cabin crew/i,
    skills:["Guest experience & service recovery","Revenue management & yield optimisation","Multi-department operations coordination","Multilingual / cultural fluency"],
    trends:["Experience-led travel over transactional bookings","AI-driven dynamic pricing","Sustainability-conscious travel demand"],
    grow:[
      { skill:"Revenue management & OTA platform literacy", why:"Pricing decisions increasingly drive margin more than volume alone." },
      { skill:"Cross-department rotation (F&B, front office, housekeeping)", why:"Senior hospitality leaders are judged on the whole guest journey, not one department." },
      { skill:"Guest-experience data & feedback systems", why:"Reviews and NPS now shape revenue directly — measure what guests actually feel." }
    ],
    courses:[
      { name:"Hospitality management certificates", by:"eCornell" },
      { name:"Revenue management courses", by:"Coursera" },
      { name:"Aviation & travel certifications", by:"IATA" },
      { name:"Hotel management diplomas", by:"Institutes of Hotel Management, India" }
    ],
    levelUp:[
      "Resolve one recurring guest complaint at its root cause, not just the symptom.",
      "Rotate through one adjacent department for cross-training.",
      "Take ownership of one guest-satisfaction metric.",
      "Learn the revenue/OTA systems even outside your own role."
    ],
    caseStudies:[
      { title:"The Ritz-Carlton's $2,000 rule",
        body:"Every Ritz-Carlton employee is empowered to spend up to $2,000 per guest, without manager approval, to fix a problem on the spot. The policy became one of the most widely taught service-excellence case studies in business schools worldwide.",
        takeaway:"Trusting frontline staff with real authority is what turns good service into legendary service." },
      { title:"Southwest Airlines: hire for attitude, train for skill",
        body:"Southwest built its hiring and promotion culture around personality and attitude over pedigree, training skills afterward. Many of its senior leaders started as gate agents or flight attendants — a deliberate, culture-first internal ladder that helped it stay consistently profitable in a brutal industry.",
        takeaway:"A strong internal-promotion culture can be a bigger competitive advantage than route networks or fleet size." }
    ],
    story:{
      title:"From a run-down motel to a hospitality philosophy",
      body:"Chip Conley left a promising finance career at 26 to buy a rundown San Francisco motel, building it into Joie de Vivre Hospitality — one of the largest boutique hotel brands in the US. He later brought that same 'hospitality thinking' to Airbnb as a strategic advisor, proving hospitality expertise travels far beyond hotels.",
      quote:"The most important things in life aren't things — in hospitality, that means people." },
    ladder:[
      { title:"Trainee / Guest Service Associate", years:"0–1 yrs", focus:"Learning service standards under supervision.", re:/trainee|intern|associate/i },
      { title:"Executive / Officer (Front Office, F&B, Cabin Crew)", years:"1–3 yrs", focus:"Delivers service independently for a shift or section." },
      { title:"Senior Executive / Duty Manager", years:"3–6 yrs", focus:"Owns a shift or department's guest experience.", re:/senior executive|duty manager|supervisor/i },
      { title:"Department Head / Asst. General Manager", years:"6–10 yrs", focus:"Owns a whole department's performance and staff.", re:/department head|assistant general manager/i },
      { title:"General Manager / VP Operations / Regional Director", years:"10+ yrs", focus:"Owns a property or region's full P&L.", re:/general manager|vp operations|regional director/i }
    ] },

  { match:/media|journalis|broadcast|entertainment|\bfilm\b|\bott\b|publishing|newsroom/i,
    skills:["Storytelling across formats (video/audio/text)","Audience analytics & platform algorithms","Editorial judgement & fact-checking","Multi-platform content production"],
    trends:["Short-form & creator-led content","AI-assisted editing & content generation","Subscription/OTT models reshaping revenue"],
    grow:[
      { skill:"Multi-format production (video/audio editing tools)", why:"Single-format specialists are being squeezed; format-flexible creators are not." },
      { skill:"Audience & platform analytics literacy", why:"Understanding the algorithm is now part of the craft, not a separate job." },
      { skill:"Personal brand & byline building", why:"In media, your name becoming trusted is itself a career asset." }
    ],
    courses:[
      { name:"Journalism courses", by:"Google News Initiative" },
      { name:"Journalism & media courses", by:"Reuters Institute / Poynter" },
      { name:"Video & content production certifications", by:"Adobe / YouTube Creator Academy" },
      { name:"Data journalism courses", by:"Coursera" }
    ],
    levelUp:[
      "Build a portfolio of your best-performing pieces with audience data attached.",
      "Learn one new format (podcast, short video, newsletter).",
      "Pitch one investigative or data-driven story beyond your usual beat.",
      "Build a public presence (byline recognition, social following) around your specialism."
    ],
    caseStudies:[
      { title:"The New York Times' digital pivot",
        body:"Facing a collapsing print-advertising model, The New York Times rebuilt itself around digital subscriptions, eventually surpassing 10 million subscribers. It is one of the most widely studied examples of an entire legacy industry successfully retraining and repositioning for a digital-first world.",
        takeaway:"A whole profession can successfully reinvent its business model — but only by retraining, not just relaunching." },
      { title:"Netflix's local-language original content bet",
        body:"Netflix shifted from a DVD-by-mail service to a global content powerhouse partly by investing heavily in local-language original productions — including Indian originals — to win regional audiences rather than exporting one global catalogue everywhere.",
        takeaway:"Winning a new market often means building for it locally, not just distributing to it." }
    ],
    story:{
      title:"From a local news anchor to a global media empire",
      body:"Oprah Winfrey began as a local Nashville news anchor after a difficult childhood, working her way up through local television before building a global media empire spanning television, publishing and production — one of the most cited career-ladder stories in media.",
      quote:"Turn your wounds into wisdom." },
    ladder:[
      { title:"Trainee Journalist / Production Assistant", years:"0–1 yrs", focus:"Research, fact-checking and production support.", re:/trainee|production assistant|intern/i },
      { title:"Correspondent / Content Writer / Jr. Producer", years:"1–3 yrs", focus:"Produces content independently on a beat or format." },
      { title:"Senior Correspondent / Producer / Content Lead", years:"3–6 yrs", focus:"Owns a beat, show or content vertical.", re:/senior correspondent|producer|content lead/i },
      { title:"Editor / Senior Producer / Bureau Chief", years:"6–10 yrs", focus:"Sets editorial direction and manages a team.", re:/\beditor\b|senior producer|bureau chief/i },
      { title:"Editor-in-Chief / Head of Content / Creative Director", years:"10+ yrs", focus:"Owns editorial or creative strategy for the whole outlet.", re:/editor-in-chief|head of content|creative director/i }
    ] },

  { match:/government|public sector|civil service|\bngo\b|non-?profit|policy|bureaucrac/i,
    skills:["Policy analysis & public communication","Stakeholder & community engagement","Program & grant management","Data-driven public accountability"],
    trends:["Digital governance & e-service delivery","Outcome-based funding & impact measurement","Public-private partnership models"],
    grow:[
      { skill:"Program monitoring & evaluation (M&E)", why:"Funders and citizens increasingly demand proof of outcomes, not just activity." },
      { skill:"Public communication & stakeholder management", why:"Policy only works if it's understood and trusted by the people it affects." },
      { skill:"Digital governance / e-service tools", why:"Service delivery is moving online — fluency here directly affects your program's reach." }
    ],
    courses:[
      { name:"Public policy courses", by:"Harvard Kennedy School via edX/Coursera" },
      { name:"Project management for the social sector (PMD Pro)", by:"APMG International" },
      { name:"E-governance certification programs", by:"Government of India" },
      { name:"NGO management diplomas", by:"TISS" }
    ],
    levelUp:[
      "Lead one measurable program or project and document its outcomes.",
      "Build one relationship with a cross-sector partner (private, media, community).",
      "Learn one data or e-governance tool used in your department.",
      "Volunteer for one cross-departmental committee or task force."
    ],
    caseStudies:[
      { title:"Delhi's government-school turnaround",
        body:"Starting in 2015, Delhi's government invested heavily in school infrastructure, teacher training and School Management Committees. Learning outcomes and board results in government schools improved significantly, making it one of the most widely studied public-sector education turnarounds in India.",
        takeaway:"Sustained investment in frontline capability, not just policy announcements, is what moves outcomes." },
      { title:"Aadhaar: scaling digital identity to 1.3 billion people",
        body:"India built and scaled a biometric digital-identity system to over a billion residents, becoming a global reference case for large-scale public digital infrastructure — built and delivered substantially by public servants and technologists working inside government.",
        takeaway:"Government can execute genuinely world-leading technical projects when given a clear mandate and the right expertise." }
    ],
    story:{
      title:"The man who built a nation's white revolution",
      body:"Dr. Verghese Kurien built India's dairy cooperative movement from a small, dusty town — Anand — into a system (later Amul, via the National Dairy Development Board) that transformed India from a milk-deficient country into the world's largest milk producer, largely by building durable institutions rather than one-off projects.",
      quote:"If you want to reach a goal, you must see the reaching in your own mind before you actually arrive." },
    ladder:[
      { title:"Trainee / Junior Program Associate", years:"0–1 yrs", focus:"Supporting program delivery and documentation.", re:/trainee|junior program associate|intern/i },
      { title:"Program Officer / Section Officer", years:"1–4 yrs", focus:"Runs a program or process area with defined scope." },
      { title:"Senior Program Officer / Program Manager", years:"4–8 yrs", focus:"Owns a program's outcomes and a small team.", re:/senior program officer|program manager|under secretary/i },
      { title:"Deputy Director / Program Director", years:"8–14 yrs", focus:"Sets strategy for a portfolio of programs.", re:/deputy director|program director|joint secretary/i },
      { title:"Director / Secretary / Executive Director", years:"14+ yrs", focus:"Owns strategy and accountability for the whole organisation.", re:/\bdirector\b|\bsecretary\b|executive director/i }
    ] },

  { match:/.*/,
    skills:["Clear written & verbal communication","Prioritisation and time management","Basic data literacy","Collaboration across functions"],
    trends:["AI augmentation of routine tasks","Skills-based hiring over titles","Continuous upskilling as the norm"],
    grow:[
      { skill:"Communication & structured writing", why:"The single most transferable career skill — it upgrades every other skill you have." },
      { skill:"Digital & AI tool fluency", why:"Every role now has software leverage; find and master yours." },
      { skill:"Project management basics", why:"Coordinating work is the bridge from doing to leading." }
    ],
    courses:[
      { name:"Google Project Management certificate", by:"Coursera" },
      { name:"Public speaking practice", by:"Toastmasters International" },
      { name:"Role-based learning paths", by:"LinkedIn Learning" },
      { name:"NPTEL / SWAYAM university courses", by:"Govt. of India, free" }
    ],
    levelUp:[
      "Write down what the next level looks like — and ask your manager to confirm it.",
      "Volunteer for one visible cross-team project this quarter.",
      "Keep a 'brag file' of wins; review it before every appraisal conversation.",
      "Find one mentor above your level and meet them monthly."
    ],
    caseStudies:[
      { title:"IBM's century of reinvention",
        body:"IBM has rebuilt its core business at least three times over more than a century — from punch-card machines to mainframes to services to cloud and AI — retraining large parts of its workforce each time rather than simply replacing it. It is often cited as proof that a career, like a company, can survive multiple reinventions.",
        takeaway:"The skill is staying willing to reinvent, not picking the one skill that lasts forever." },
      { title:"3M's '15% time'",
        body:"3M let employees spend 15% of their working time on self-directed projects with no obligation to show results — a policy that produced inventions like the Post-it Note and later inspired Google's famous '20% time'.",
        takeaway:"Protected time for self-directed exploration regularly produces outsized career and business wins." }
    ],
    story:{
      title:"1,009 rejections",
      body:"Harland Sanders was 62 and living off a small pension when he began driving across America to sell his fried-chicken recipe, sleeping in his car between meetings. Legend counts more than a thousand rejections before a restaurant said yes. KFC became one of the world's largest food chains — built by a man who refused to believe he was finished.",
      quote:"I made a resolve then that I was going to amount to something if I could." },
    ladder:[
      { title:"Trainee / Associate / Executive", years:"0–1 yrs", focus:"Learning the role's core tools and processes.", re:/trainee|intern|associate/i },
      { title:"Officer / Specialist / Analyst", years:"1–3 yrs", focus:"Handles defined responsibilities with growing independence." },
      { title:"Senior Specialist / Team Lead", years:"3–6 yrs", focus:"Owns a work area and supports junior colleagues.", re:/senior|team lead/i },
      { title:"Manager / Assistant Manager", years:"6–10 yrs", focus:"Owns a team's targets and performance.", re:/\bmanager\b/i },
      { title:"Senior Manager / Head of Department / Director", years:"10+ yrs", focus:"Sets strategy for a function or department.", re:/senior manager|head of department|\bdirector\b/i }
    ] }
];

/* Finds which ladder rung best matches a job title, checked from executive
   down to entry (first match wins). Falls back to the core IC rung (index 1)
   when nothing matches — a plain title with no seniority modifier is most
   often a core individual-contributor role, not an intern or executive. */

